// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: organization.proto

package com.psiphiglobal.identity.proto;

/**
 * Protobuf enum {@code identity.proto.AutoValidationMechanism}
 */
public enum AutoValidationMechanism
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>UNKNOWN = 0;</code>
   */
  UNKNOWN(0),
  /**
   * <code>NONE = 1;</code>
   */
  NONE(1),
  /**
   * <code>DNS = 2;</code>
   */
  DNS(2),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>UNKNOWN = 0;</code>
   */
  public static final int UNKNOWN_VALUE = 0;
  /**
   * <code>NONE = 1;</code>
   */
  public static final int NONE_VALUE = 1;
  /**
   * <code>DNS = 2;</code>
   */
  public static final int DNS_VALUE = 2;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static AutoValidationMechanism valueOf(int value) {
    return forNumber(value);
  }

  public static AutoValidationMechanism forNumber(int value) {
    switch (value) {
      case 0: return UNKNOWN;
      case 1: return NONE;
      case 2: return DNS;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<AutoValidationMechanism>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      AutoValidationMechanism> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<AutoValidationMechanism>() {
          public AutoValidationMechanism findValueByNumber(int number) {
            return AutoValidationMechanism.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return com.psiphiglobal.identity.proto.OrganizationOuterClass.getDescriptor().getEnumTypes().get(1);
  }

  private static final AutoValidationMechanism[] VALUES = values();

  public static AutoValidationMechanism valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private AutoValidationMechanism(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:identity.proto.AutoValidationMechanism)
}

