// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: organization.proto

package com.psiphiglobal.identity.proto;

/**
 * Protobuf enum {@code identity.proto.CertificateStatus}
 */
public enum CertificateStatus
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>ACTIVE = 0;</code>
   */
  ACTIVE(0),
  /**
   * <code>EXPIRED = 1;</code>
   */
  EXPIRED(1),
  /**
   * <code>BLOCKED = 2;</code>
   */
  BLOCKED(2),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>ACTIVE = 0;</code>
   */
  public static final int ACTIVE_VALUE = 0;
  /**
   * <code>EXPIRED = 1;</code>
   */
  public static final int EXPIRED_VALUE = 1;
  /**
   * <code>BLOCKED = 2;</code>
   */
  public static final int BLOCKED_VALUE = 2;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static CertificateStatus valueOf(int value) {
    return forNumber(value);
  }

  public static CertificateStatus forNumber(int value) {
    switch (value) {
      case 0: return ACTIVE;
      case 1: return EXPIRED;
      case 2: return BLOCKED;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<CertificateStatus>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      CertificateStatus> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<CertificateStatus>() {
          public CertificateStatus findValueByNumber(int number) {
            return CertificateStatus.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return com.psiphiglobal.identity.proto.OrganizationOuterClass.getDescriptor().getEnumTypes().get(0);
  }

  private static final CertificateStatus[] VALUES = values();

  public static CertificateStatus valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private CertificateStatus(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:identity.proto.CertificateStatus)
}

