// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: organization.proto

package com.psiphiglobal.identity.proto;

public interface CertificateDataOrBuilder extends
    // @@protoc_insertion_point(interface_extends:identity.proto.CertificateData)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string domain_name = 1;</code>
   */
  java.lang.String getDomainName();
  /**
   * <code>string domain_name = 1;</code>
   */
  com.google.protobuf.ByteString
      getDomainNameBytes();

  /**
   * <code>.identity.proto.OrganizationDetails org_details = 2;</code>
   */
  boolean hasOrgDetails();
  /**
   * <code>.identity.proto.OrganizationDetails org_details = 2;</code>
   */
  com.psiphiglobal.identity.proto.OrganizationDetails getOrgDetails();
  /**
   * <code>.identity.proto.OrganizationDetails org_details = 2;</code>
   */
  com.psiphiglobal.identity.proto.OrganizationDetailsOrBuilder getOrgDetailsOrBuilder();

  /**
   * <code>.identity.proto.PublicKey public_key = 3;</code>
   */
  boolean hasPublicKey();
  /**
   * <code>.identity.proto.PublicKey public_key = 3;</code>
   */
  com.psiphiglobal.identity.proto.PublicKey getPublicKey();
  /**
   * <code>.identity.proto.PublicKey public_key = 3;</code>
   */
  com.psiphiglobal.identity.proto.PublicKeyOrBuilder getPublicKeyOrBuilder();
}
