// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: common.proto

package com.psiphiglobal.identity.proto;

public final class Common {
  private Common() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_identity_proto_PublicKey_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_identity_proto_PublicKey_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_identity_proto_Signature_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_identity_proto_Signature_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014common.proto\022\016identity.proto\"\177\n\tPublic" +
      "Key\0226\n\talgorithm\030\001 \001(\0162#.identity.proto." +
      "PublicKey.Algorithm\022\014\n\004data\030\002 \001(\014\",\n\tAlg" +
      "orithm\022\013\n\007UNKNOWN\020\000\022\007\n\003RSA\020\001\022\t\n\005ECDSA\020\002\"" +
      "D\n\tSignature\022\026\n\016signer_cert_id\030\001 \001(\t\022\014\n\004" +
      "data\030\002 \001(\014\022\021\n\ttimestamp\030\003 \001(\004B-\n\037com.psi" +
      "phiglobal.identity.protoP\001Z\010identityb\006pr" +
      "oto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_identity_proto_PublicKey_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_identity_proto_PublicKey_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_identity_proto_PublicKey_descriptor,
        new java.lang.String[] { "Algorithm", "Data", });
    internal_static_identity_proto_Signature_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_identity_proto_Signature_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_identity_proto_Signature_descriptor,
        new java.lang.String[] { "SignerCertId", "Data", "Timestamp", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
