// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: common.proto

package com.psiphiglobal.identity.proto;

public final class Common {
  private Common() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface PublicKeyOrBuilder extends
      // @@protoc_insertion_point(interface_extends:identity.proto.PublicKey)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.identity.proto.PublicKey.Algorithm algorithm = 1;</code>
     */
    int getAlgorithmValue();
    /**
     * <code>.identity.proto.PublicKey.Algorithm algorithm = 1;</code>
     */
    com.psiphiglobal.identity.proto.Common.PublicKey.Algorithm getAlgorithm();

    /**
     * <code>bytes data = 2;</code>
     */
    com.google.protobuf.ByteString getData();
  }
  /**
   * Protobuf type {@code identity.proto.PublicKey}
   */
  public  static final class PublicKey extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:identity.proto.PublicKey)
      PublicKeyOrBuilder {
    // Use PublicKey.newBuilder() to construct.
    private PublicKey(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private PublicKey() {
      algorithm_ = 0;
      data_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private PublicKey(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();

              algorithm_ = rawValue;
              break;
            }
            case 18: {

              data_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.psiphiglobal.identity.proto.Common.internal_static_identity_proto_PublicKey_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.psiphiglobal.identity.proto.Common.internal_static_identity_proto_PublicKey_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.psiphiglobal.identity.proto.Common.PublicKey.class, com.psiphiglobal.identity.proto.Common.PublicKey.Builder.class);
    }

    /**
     * Protobuf enum {@code identity.proto.PublicKey.Algorithm}
     */
    public enum Algorithm
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>UNKNOWN = 0;</code>
       */
      UNKNOWN(0),
      /**
       * <code>RSA = 1;</code>
       */
      RSA(1),
      /**
       * <code>ECDSA = 2;</code>
       */
      ECDSA(2),
      UNRECOGNIZED(-1),
      ;

      /**
       * <code>UNKNOWN = 0;</code>
       */
      public static final int UNKNOWN_VALUE = 0;
      /**
       * <code>RSA = 1;</code>
       */
      public static final int RSA_VALUE = 1;
      /**
       * <code>ECDSA = 2;</code>
       */
      public static final int ECDSA_VALUE = 2;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static Algorithm valueOf(int value) {
        return forNumber(value);
      }

      public static Algorithm forNumber(int value) {
        switch (value) {
          case 0: return UNKNOWN;
          case 1: return RSA;
          case 2: return ECDSA;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<Algorithm>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          Algorithm> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Algorithm>() {
              public Algorithm findValueByNumber(int number) {
                return Algorithm.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.psiphiglobal.identity.proto.Common.PublicKey.getDescriptor().getEnumTypes().get(0);
      }

      private static final Algorithm[] VALUES = values();

      public static Algorithm valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private Algorithm(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:identity.proto.PublicKey.Algorithm)
    }

    public static final int ALGORITHM_FIELD_NUMBER = 1;
    private int algorithm_;
    /**
     * <code>.identity.proto.PublicKey.Algorithm algorithm = 1;</code>
     */
    public int getAlgorithmValue() {
      return algorithm_;
    }
    /**
     * <code>.identity.proto.PublicKey.Algorithm algorithm = 1;</code>
     */
    public com.psiphiglobal.identity.proto.Common.PublicKey.Algorithm getAlgorithm() {
      com.psiphiglobal.identity.proto.Common.PublicKey.Algorithm result = com.psiphiglobal.identity.proto.Common.PublicKey.Algorithm.valueOf(algorithm_);
      return result == null ? com.psiphiglobal.identity.proto.Common.PublicKey.Algorithm.UNRECOGNIZED : result;
    }

    public static final int DATA_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString data_;
    /**
     * <code>bytes data = 2;</code>
     */
    public com.google.protobuf.ByteString getData() {
      return data_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (algorithm_ != com.psiphiglobal.identity.proto.Common.PublicKey.Algorithm.UNKNOWN.getNumber()) {
        output.writeEnum(1, algorithm_);
      }
      if (!data_.isEmpty()) {
        output.writeBytes(2, data_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (algorithm_ != com.psiphiglobal.identity.proto.Common.PublicKey.Algorithm.UNKNOWN.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, algorithm_);
      }
      if (!data_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, data_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.psiphiglobal.identity.proto.Common.PublicKey)) {
        return super.equals(obj);
      }
      com.psiphiglobal.identity.proto.Common.PublicKey other = (com.psiphiglobal.identity.proto.Common.PublicKey) obj;

      boolean result = true;
      result = result && algorithm_ == other.algorithm_;
      result = result && getData()
          .equals(other.getData());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ALGORITHM_FIELD_NUMBER;
      hash = (53 * hash) + algorithm_;
      hash = (37 * hash) + DATA_FIELD_NUMBER;
      hash = (53 * hash) + getData().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.psiphiglobal.identity.proto.Common.PublicKey parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.psiphiglobal.identity.proto.Common.PublicKey parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.psiphiglobal.identity.proto.Common.PublicKey parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.psiphiglobal.identity.proto.Common.PublicKey parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.psiphiglobal.identity.proto.Common.PublicKey parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.psiphiglobal.identity.proto.Common.PublicKey parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.psiphiglobal.identity.proto.Common.PublicKey parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.psiphiglobal.identity.proto.Common.PublicKey parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.psiphiglobal.identity.proto.Common.PublicKey parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.psiphiglobal.identity.proto.Common.PublicKey parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.psiphiglobal.identity.proto.Common.PublicKey prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code identity.proto.PublicKey}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:identity.proto.PublicKey)
        com.psiphiglobal.identity.proto.Common.PublicKeyOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.psiphiglobal.identity.proto.Common.internal_static_identity_proto_PublicKey_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.psiphiglobal.identity.proto.Common.internal_static_identity_proto_PublicKey_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.psiphiglobal.identity.proto.Common.PublicKey.class, com.psiphiglobal.identity.proto.Common.PublicKey.Builder.class);
      }

      // Construct using com.psiphiglobal.identity.proto.Common.PublicKey.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        algorithm_ = 0;

        data_ = com.google.protobuf.ByteString.EMPTY;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.psiphiglobal.identity.proto.Common.internal_static_identity_proto_PublicKey_descriptor;
      }

      public com.psiphiglobal.identity.proto.Common.PublicKey getDefaultInstanceForType() {
        return com.psiphiglobal.identity.proto.Common.PublicKey.getDefaultInstance();
      }

      public com.psiphiglobal.identity.proto.Common.PublicKey build() {
        com.psiphiglobal.identity.proto.Common.PublicKey result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.psiphiglobal.identity.proto.Common.PublicKey buildPartial() {
        com.psiphiglobal.identity.proto.Common.PublicKey result = new com.psiphiglobal.identity.proto.Common.PublicKey(this);
        result.algorithm_ = algorithm_;
        result.data_ = data_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.psiphiglobal.identity.proto.Common.PublicKey) {
          return mergeFrom((com.psiphiglobal.identity.proto.Common.PublicKey)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.psiphiglobal.identity.proto.Common.PublicKey other) {
        if (other == com.psiphiglobal.identity.proto.Common.PublicKey.getDefaultInstance()) return this;
        if (other.algorithm_ != 0) {
          setAlgorithmValue(other.getAlgorithmValue());
        }
        if (other.getData() != com.google.protobuf.ByteString.EMPTY) {
          setData(other.getData());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.psiphiglobal.identity.proto.Common.PublicKey parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.psiphiglobal.identity.proto.Common.PublicKey) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int algorithm_ = 0;
      /**
       * <code>.identity.proto.PublicKey.Algorithm algorithm = 1;</code>
       */
      public int getAlgorithmValue() {
        return algorithm_;
      }
      /**
       * <code>.identity.proto.PublicKey.Algorithm algorithm = 1;</code>
       */
      public Builder setAlgorithmValue(int value) {
        algorithm_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.identity.proto.PublicKey.Algorithm algorithm = 1;</code>
       */
      public com.psiphiglobal.identity.proto.Common.PublicKey.Algorithm getAlgorithm() {
        com.psiphiglobal.identity.proto.Common.PublicKey.Algorithm result = com.psiphiglobal.identity.proto.Common.PublicKey.Algorithm.valueOf(algorithm_);
        return result == null ? com.psiphiglobal.identity.proto.Common.PublicKey.Algorithm.UNRECOGNIZED : result;
      }
      /**
       * <code>.identity.proto.PublicKey.Algorithm algorithm = 1;</code>
       */
      public Builder setAlgorithm(com.psiphiglobal.identity.proto.Common.PublicKey.Algorithm value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        algorithm_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.identity.proto.PublicKey.Algorithm algorithm = 1;</code>
       */
      public Builder clearAlgorithm() {
        
        algorithm_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString data_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes data = 2;</code>
       */
      public com.google.protobuf.ByteString getData() {
        return data_;
      }
      /**
       * <code>bytes data = 2;</code>
       */
      public Builder setData(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        data_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes data = 2;</code>
       */
      public Builder clearData() {
        
        data_ = getDefaultInstance().getData();
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:identity.proto.PublicKey)
    }

    // @@protoc_insertion_point(class_scope:identity.proto.PublicKey)
    private static final com.psiphiglobal.identity.proto.Common.PublicKey DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.psiphiglobal.identity.proto.Common.PublicKey();
    }

    public static com.psiphiglobal.identity.proto.Common.PublicKey getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<PublicKey>
        PARSER = new com.google.protobuf.AbstractParser<PublicKey>() {
      public PublicKey parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new PublicKey(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<PublicKey> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<PublicKey> getParserForType() {
      return PARSER;
    }

    public com.psiphiglobal.identity.proto.Common.PublicKey getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface SignatureOrBuilder extends
      // @@protoc_insertion_point(interface_extends:identity.proto.Signature)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string signer_cert_id = 1;</code>
     */
    java.lang.String getSignerCertId();
    /**
     * <code>string signer_cert_id = 1;</code>
     */
    com.google.protobuf.ByteString
        getSignerCertIdBytes();

    /**
     * <code>.identity.proto.Signature.Algorithm algorithm = 2;</code>
     */
    int getAlgorithmValue();
    /**
     * <code>.identity.proto.Signature.Algorithm algorithm = 2;</code>
     */
    com.psiphiglobal.identity.proto.Common.Signature.Algorithm getAlgorithm();

    /**
     * <code>bytes data = 3;</code>
     */
    com.google.protobuf.ByteString getData();

    /**
     * <code>uint64 timestamp = 4;</code>
     */
    long getTimestamp();
  }
  /**
   * Protobuf type {@code identity.proto.Signature}
   */
  public  static final class Signature extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:identity.proto.Signature)
      SignatureOrBuilder {
    // Use Signature.newBuilder() to construct.
    private Signature(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Signature() {
      signerCertId_ = "";
      algorithm_ = 0;
      data_ = com.google.protobuf.ByteString.EMPTY;
      timestamp_ = 0L;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private Signature(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              signerCertId_ = s;
              break;
            }
            case 16: {
              int rawValue = input.readEnum();

              algorithm_ = rawValue;
              break;
            }
            case 26: {

              data_ = input.readBytes();
              break;
            }
            case 32: {

              timestamp_ = input.readUInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.psiphiglobal.identity.proto.Common.internal_static_identity_proto_Signature_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.psiphiglobal.identity.proto.Common.internal_static_identity_proto_Signature_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.psiphiglobal.identity.proto.Common.Signature.class, com.psiphiglobal.identity.proto.Common.Signature.Builder.class);
    }

    /**
     * Protobuf enum {@code identity.proto.Signature.Algorithm}
     */
    public enum Algorithm
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>UNKNOWN = 0;</code>
       */
      UNKNOWN(0),
      /**
       * <code>SHA256_RSA = 1;</code>
       */
      SHA256_RSA(1),
      /**
       * <code>SHA256_ECDSA = 2;</code>
       */
      SHA256_ECDSA(2),
      UNRECOGNIZED(-1),
      ;

      /**
       * <code>UNKNOWN = 0;</code>
       */
      public static final int UNKNOWN_VALUE = 0;
      /**
       * <code>SHA256_RSA = 1;</code>
       */
      public static final int SHA256_RSA_VALUE = 1;
      /**
       * <code>SHA256_ECDSA = 2;</code>
       */
      public static final int SHA256_ECDSA_VALUE = 2;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static Algorithm valueOf(int value) {
        return forNumber(value);
      }

      public static Algorithm forNumber(int value) {
        switch (value) {
          case 0: return UNKNOWN;
          case 1: return SHA256_RSA;
          case 2: return SHA256_ECDSA;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<Algorithm>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          Algorithm> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Algorithm>() {
              public Algorithm findValueByNumber(int number) {
                return Algorithm.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.psiphiglobal.identity.proto.Common.Signature.getDescriptor().getEnumTypes().get(0);
      }

      private static final Algorithm[] VALUES = values();

      public static Algorithm valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private Algorithm(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:identity.proto.Signature.Algorithm)
    }

    public static final int SIGNER_CERT_ID_FIELD_NUMBER = 1;
    private volatile java.lang.Object signerCertId_;
    /**
     * <code>string signer_cert_id = 1;</code>
     */
    public java.lang.String getSignerCertId() {
      java.lang.Object ref = signerCertId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        signerCertId_ = s;
        return s;
      }
    }
    /**
     * <code>string signer_cert_id = 1;</code>
     */
    public com.google.protobuf.ByteString
        getSignerCertIdBytes() {
      java.lang.Object ref = signerCertId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        signerCertId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ALGORITHM_FIELD_NUMBER = 2;
    private int algorithm_;
    /**
     * <code>.identity.proto.Signature.Algorithm algorithm = 2;</code>
     */
    public int getAlgorithmValue() {
      return algorithm_;
    }
    /**
     * <code>.identity.proto.Signature.Algorithm algorithm = 2;</code>
     */
    public com.psiphiglobal.identity.proto.Common.Signature.Algorithm getAlgorithm() {
      com.psiphiglobal.identity.proto.Common.Signature.Algorithm result = com.psiphiglobal.identity.proto.Common.Signature.Algorithm.valueOf(algorithm_);
      return result == null ? com.psiphiglobal.identity.proto.Common.Signature.Algorithm.UNRECOGNIZED : result;
    }

    public static final int DATA_FIELD_NUMBER = 3;
    private com.google.protobuf.ByteString data_;
    /**
     * <code>bytes data = 3;</code>
     */
    public com.google.protobuf.ByteString getData() {
      return data_;
    }

    public static final int TIMESTAMP_FIELD_NUMBER = 4;
    private long timestamp_;
    /**
     * <code>uint64 timestamp = 4;</code>
     */
    public long getTimestamp() {
      return timestamp_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getSignerCertIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, signerCertId_);
      }
      if (algorithm_ != com.psiphiglobal.identity.proto.Common.Signature.Algorithm.UNKNOWN.getNumber()) {
        output.writeEnum(2, algorithm_);
      }
      if (!data_.isEmpty()) {
        output.writeBytes(3, data_);
      }
      if (timestamp_ != 0L) {
        output.writeUInt64(4, timestamp_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getSignerCertIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, signerCertId_);
      }
      if (algorithm_ != com.psiphiglobal.identity.proto.Common.Signature.Algorithm.UNKNOWN.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, algorithm_);
      }
      if (!data_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, data_);
      }
      if (timestamp_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(4, timestamp_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.psiphiglobal.identity.proto.Common.Signature)) {
        return super.equals(obj);
      }
      com.psiphiglobal.identity.proto.Common.Signature other = (com.psiphiglobal.identity.proto.Common.Signature) obj;

      boolean result = true;
      result = result && getSignerCertId()
          .equals(other.getSignerCertId());
      result = result && algorithm_ == other.algorithm_;
      result = result && getData()
          .equals(other.getData());
      result = result && (getTimestamp()
          == other.getTimestamp());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + SIGNER_CERT_ID_FIELD_NUMBER;
      hash = (53 * hash) + getSignerCertId().hashCode();
      hash = (37 * hash) + ALGORITHM_FIELD_NUMBER;
      hash = (53 * hash) + algorithm_;
      hash = (37 * hash) + DATA_FIELD_NUMBER;
      hash = (53 * hash) + getData().hashCode();
      hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getTimestamp());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.psiphiglobal.identity.proto.Common.Signature parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.psiphiglobal.identity.proto.Common.Signature parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.psiphiglobal.identity.proto.Common.Signature parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.psiphiglobal.identity.proto.Common.Signature parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.psiphiglobal.identity.proto.Common.Signature parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.psiphiglobal.identity.proto.Common.Signature parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.psiphiglobal.identity.proto.Common.Signature parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.psiphiglobal.identity.proto.Common.Signature parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.psiphiglobal.identity.proto.Common.Signature parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.psiphiglobal.identity.proto.Common.Signature parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.psiphiglobal.identity.proto.Common.Signature prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code identity.proto.Signature}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:identity.proto.Signature)
        com.psiphiglobal.identity.proto.Common.SignatureOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.psiphiglobal.identity.proto.Common.internal_static_identity_proto_Signature_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.psiphiglobal.identity.proto.Common.internal_static_identity_proto_Signature_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.psiphiglobal.identity.proto.Common.Signature.class, com.psiphiglobal.identity.proto.Common.Signature.Builder.class);
      }

      // Construct using com.psiphiglobal.identity.proto.Common.Signature.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        signerCertId_ = "";

        algorithm_ = 0;

        data_ = com.google.protobuf.ByteString.EMPTY;

        timestamp_ = 0L;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.psiphiglobal.identity.proto.Common.internal_static_identity_proto_Signature_descriptor;
      }

      public com.psiphiglobal.identity.proto.Common.Signature getDefaultInstanceForType() {
        return com.psiphiglobal.identity.proto.Common.Signature.getDefaultInstance();
      }

      public com.psiphiglobal.identity.proto.Common.Signature build() {
        com.psiphiglobal.identity.proto.Common.Signature result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.psiphiglobal.identity.proto.Common.Signature buildPartial() {
        com.psiphiglobal.identity.proto.Common.Signature result = new com.psiphiglobal.identity.proto.Common.Signature(this);
        result.signerCertId_ = signerCertId_;
        result.algorithm_ = algorithm_;
        result.data_ = data_;
        result.timestamp_ = timestamp_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.psiphiglobal.identity.proto.Common.Signature) {
          return mergeFrom((com.psiphiglobal.identity.proto.Common.Signature)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.psiphiglobal.identity.proto.Common.Signature other) {
        if (other == com.psiphiglobal.identity.proto.Common.Signature.getDefaultInstance()) return this;
        if (!other.getSignerCertId().isEmpty()) {
          signerCertId_ = other.signerCertId_;
          onChanged();
        }
        if (other.algorithm_ != 0) {
          setAlgorithmValue(other.getAlgorithmValue());
        }
        if (other.getData() != com.google.protobuf.ByteString.EMPTY) {
          setData(other.getData());
        }
        if (other.getTimestamp() != 0L) {
          setTimestamp(other.getTimestamp());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.psiphiglobal.identity.proto.Common.Signature parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.psiphiglobal.identity.proto.Common.Signature) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object signerCertId_ = "";
      /**
       * <code>string signer_cert_id = 1;</code>
       */
      public java.lang.String getSignerCertId() {
        java.lang.Object ref = signerCertId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          signerCertId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string signer_cert_id = 1;</code>
       */
      public com.google.protobuf.ByteString
          getSignerCertIdBytes() {
        java.lang.Object ref = signerCertId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          signerCertId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string signer_cert_id = 1;</code>
       */
      public Builder setSignerCertId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        signerCertId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string signer_cert_id = 1;</code>
       */
      public Builder clearSignerCertId() {
        
        signerCertId_ = getDefaultInstance().getSignerCertId();
        onChanged();
        return this;
      }
      /**
       * <code>string signer_cert_id = 1;</code>
       */
      public Builder setSignerCertIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        signerCertId_ = value;
        onChanged();
        return this;
      }

      private int algorithm_ = 0;
      /**
       * <code>.identity.proto.Signature.Algorithm algorithm = 2;</code>
       */
      public int getAlgorithmValue() {
        return algorithm_;
      }
      /**
       * <code>.identity.proto.Signature.Algorithm algorithm = 2;</code>
       */
      public Builder setAlgorithmValue(int value) {
        algorithm_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.identity.proto.Signature.Algorithm algorithm = 2;</code>
       */
      public com.psiphiglobal.identity.proto.Common.Signature.Algorithm getAlgorithm() {
        com.psiphiglobal.identity.proto.Common.Signature.Algorithm result = com.psiphiglobal.identity.proto.Common.Signature.Algorithm.valueOf(algorithm_);
        return result == null ? com.psiphiglobal.identity.proto.Common.Signature.Algorithm.UNRECOGNIZED : result;
      }
      /**
       * <code>.identity.proto.Signature.Algorithm algorithm = 2;</code>
       */
      public Builder setAlgorithm(com.psiphiglobal.identity.proto.Common.Signature.Algorithm value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        algorithm_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.identity.proto.Signature.Algorithm algorithm = 2;</code>
       */
      public Builder clearAlgorithm() {
        
        algorithm_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString data_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes data = 3;</code>
       */
      public com.google.protobuf.ByteString getData() {
        return data_;
      }
      /**
       * <code>bytes data = 3;</code>
       */
      public Builder setData(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        data_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes data = 3;</code>
       */
      public Builder clearData() {
        
        data_ = getDefaultInstance().getData();
        onChanged();
        return this;
      }

      private long timestamp_ ;
      /**
       * <code>uint64 timestamp = 4;</code>
       */
      public long getTimestamp() {
        return timestamp_;
      }
      /**
       * <code>uint64 timestamp = 4;</code>
       */
      public Builder setTimestamp(long value) {
        
        timestamp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint64 timestamp = 4;</code>
       */
      public Builder clearTimestamp() {
        
        timestamp_ = 0L;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:identity.proto.Signature)
    }

    // @@protoc_insertion_point(class_scope:identity.proto.Signature)
    private static final com.psiphiglobal.identity.proto.Common.Signature DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.psiphiglobal.identity.proto.Common.Signature();
    }

    public static com.psiphiglobal.identity.proto.Common.Signature getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Signature>
        PARSER = new com.google.protobuf.AbstractParser<Signature>() {
      public Signature parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Signature(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Signature> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Signature> getParserForType() {
      return PARSER;
    }

    public com.psiphiglobal.identity.proto.Common.Signature getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_identity_proto_PublicKey_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_identity_proto_PublicKey_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_identity_proto_Signature_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_identity_proto_Signature_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014common.proto\022\016identity.proto\"\177\n\tPublic" +
      "Key\0226\n\talgorithm\030\001 \001(\0162#.identity.proto." +
      "PublicKey.Algorithm\022\014\n\004data\030\002 \001(\014\",\n\tAlg" +
      "orithm\022\013\n\007UNKNOWN\020\000\022\007\n\003RSA\020\001\022\t\n\005ECDSA\020\002\"" +
      "\270\001\n\tSignature\022\026\n\016signer_cert_id\030\001 \001(\t\0226\n" +
      "\talgorithm\030\002 \001(\0162#.identity.proto.Signat" +
      "ure.Algorithm\022\014\n\004data\030\003 \001(\014\022\021\n\ttimestamp" +
      "\030\004 \001(\004\":\n\tAlgorithm\022\013\n\007UNKNOWN\020\000\022\016\n\nSHA2" +
      "56_RSA\020\001\022\020\n\014SHA256_ECDSA\020\002B)\n\037com.psiphi" +
      "global.identity.protoB\006Commonb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_identity_proto_PublicKey_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_identity_proto_PublicKey_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_identity_proto_PublicKey_descriptor,
        new java.lang.String[] { "Algorithm", "Data", });
    internal_static_identity_proto_Signature_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_identity_proto_Signature_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_identity_proto_Signature_descriptor,
        new java.lang.String[] { "SignerCertId", "Algorithm", "Data", "Timestamp", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
