// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: organization.proto

package com.psiphiglobal.identity.proto;

public interface OrganizationDetailsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:identity.proto.OrganizationDetails)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   */
  java.lang.String getName();
  /**
   * <code>string name = 1;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>string email = 2;</code>
   */
  java.lang.String getEmail();
  /**
   * <code>string email = 2;</code>
   */
  com.google.protobuf.ByteString
      getEmailBytes();

  /**
   * <code>string country = 3;</code>
   */
  java.lang.String getCountry();
  /**
   * <code>string country = 3;</code>
   */
  com.google.protobuf.ByteString
      getCountryBytes();
}
