// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: organization.proto

package com.psiphiglobal.identity.proto;

/**
 * Protobuf type {@code identity.proto.Organization}
 */
public  final class Organization extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:identity.proto.Organization)
    OrganizationOrBuilder {
  // Use Organization.newBuilder() to construct.
  private Organization(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Organization() {
    domainName_ = "";
    primaryCertId_ = "";
    activeCerts_ = java.util.Collections.emptyList();
    expiredCerts_ = java.util.Collections.emptyList();
    blockedCerts_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private Organization(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            domainName_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            primaryCertId_ = s;
            break;
          }
          case 26: {
            if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
              activeCerts_ = new java.util.ArrayList<com.psiphiglobal.identity.proto.SignedCertificate>();
              mutable_bitField0_ |= 0x00000004;
            }
            activeCerts_.add(
                input.readMessage(com.psiphiglobal.identity.proto.SignedCertificate.parser(), extensionRegistry));
            break;
          }
          case 34: {
            if (!((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
              expiredCerts_ = new java.util.ArrayList<com.psiphiglobal.identity.proto.SignedCertificate>();
              mutable_bitField0_ |= 0x00000008;
            }
            expiredCerts_.add(
                input.readMessage(com.psiphiglobal.identity.proto.SignedCertificate.parser(), extensionRegistry));
            break;
          }
          case 42: {
            if (!((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
              blockedCerts_ = new java.util.ArrayList<com.psiphiglobal.identity.proto.SignedCertificate>();
              mutable_bitField0_ |= 0x00000010;
            }
            blockedCerts_.add(
                input.readMessage(com.psiphiglobal.identity.proto.SignedCertificate.parser(), extensionRegistry));
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
        activeCerts_ = java.util.Collections.unmodifiableList(activeCerts_);
      }
      if (((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
        expiredCerts_ = java.util.Collections.unmodifiableList(expiredCerts_);
      }
      if (((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
        blockedCerts_ = java.util.Collections.unmodifiableList(blockedCerts_);
      }
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.psiphiglobal.identity.proto.OrganizationOuterClass.internal_static_identity_proto_Organization_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.psiphiglobal.identity.proto.OrganizationOuterClass.internal_static_identity_proto_Organization_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.psiphiglobal.identity.proto.Organization.class, com.psiphiglobal.identity.proto.Organization.Builder.class);
  }

  private int bitField0_;
  public static final int DOMAIN_NAME_FIELD_NUMBER = 1;
  private volatile java.lang.Object domainName_;
  /**
   * <code>string domain_name = 1;</code>
   */
  public java.lang.String getDomainName() {
    java.lang.Object ref = domainName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      domainName_ = s;
      return s;
    }
  }
  /**
   * <code>string domain_name = 1;</code>
   */
  public com.google.protobuf.ByteString
      getDomainNameBytes() {
    java.lang.Object ref = domainName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      domainName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PRIMARY_CERT_ID_FIELD_NUMBER = 2;
  private volatile java.lang.Object primaryCertId_;
  /**
   * <code>string primary_cert_id = 2;</code>
   */
  public java.lang.String getPrimaryCertId() {
    java.lang.Object ref = primaryCertId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      primaryCertId_ = s;
      return s;
    }
  }
  /**
   * <code>string primary_cert_id = 2;</code>
   */
  public com.google.protobuf.ByteString
      getPrimaryCertIdBytes() {
    java.lang.Object ref = primaryCertId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      primaryCertId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ACTIVE_CERTS_FIELD_NUMBER = 3;
  private java.util.List<com.psiphiglobal.identity.proto.SignedCertificate> activeCerts_;
  /**
   * <code>repeated .identity.proto.SignedCertificate active_certs = 3;</code>
   */
  public java.util.List<com.psiphiglobal.identity.proto.SignedCertificate> getActiveCertsList() {
    return activeCerts_;
  }
  /**
   * <code>repeated .identity.proto.SignedCertificate active_certs = 3;</code>
   */
  public java.util.List<? extends com.psiphiglobal.identity.proto.SignedCertificateOrBuilder> 
      getActiveCertsOrBuilderList() {
    return activeCerts_;
  }
  /**
   * <code>repeated .identity.proto.SignedCertificate active_certs = 3;</code>
   */
  public int getActiveCertsCount() {
    return activeCerts_.size();
  }
  /**
   * <code>repeated .identity.proto.SignedCertificate active_certs = 3;</code>
   */
  public com.psiphiglobal.identity.proto.SignedCertificate getActiveCerts(int index) {
    return activeCerts_.get(index);
  }
  /**
   * <code>repeated .identity.proto.SignedCertificate active_certs = 3;</code>
   */
  public com.psiphiglobal.identity.proto.SignedCertificateOrBuilder getActiveCertsOrBuilder(
      int index) {
    return activeCerts_.get(index);
  }

  public static final int EXPIRED_CERTS_FIELD_NUMBER = 4;
  private java.util.List<com.psiphiglobal.identity.proto.SignedCertificate> expiredCerts_;
  /**
   * <code>repeated .identity.proto.SignedCertificate expired_certs = 4;</code>
   */
  public java.util.List<com.psiphiglobal.identity.proto.SignedCertificate> getExpiredCertsList() {
    return expiredCerts_;
  }
  /**
   * <code>repeated .identity.proto.SignedCertificate expired_certs = 4;</code>
   */
  public java.util.List<? extends com.psiphiglobal.identity.proto.SignedCertificateOrBuilder> 
      getExpiredCertsOrBuilderList() {
    return expiredCerts_;
  }
  /**
   * <code>repeated .identity.proto.SignedCertificate expired_certs = 4;</code>
   */
  public int getExpiredCertsCount() {
    return expiredCerts_.size();
  }
  /**
   * <code>repeated .identity.proto.SignedCertificate expired_certs = 4;</code>
   */
  public com.psiphiglobal.identity.proto.SignedCertificate getExpiredCerts(int index) {
    return expiredCerts_.get(index);
  }
  /**
   * <code>repeated .identity.proto.SignedCertificate expired_certs = 4;</code>
   */
  public com.psiphiglobal.identity.proto.SignedCertificateOrBuilder getExpiredCertsOrBuilder(
      int index) {
    return expiredCerts_.get(index);
  }

  public static final int BLOCKED_CERTS_FIELD_NUMBER = 5;
  private java.util.List<com.psiphiglobal.identity.proto.SignedCertificate> blockedCerts_;
  /**
   * <code>repeated .identity.proto.SignedCertificate blocked_certs = 5;</code>
   */
  public java.util.List<com.psiphiglobal.identity.proto.SignedCertificate> getBlockedCertsList() {
    return blockedCerts_;
  }
  /**
   * <code>repeated .identity.proto.SignedCertificate blocked_certs = 5;</code>
   */
  public java.util.List<? extends com.psiphiglobal.identity.proto.SignedCertificateOrBuilder> 
      getBlockedCertsOrBuilderList() {
    return blockedCerts_;
  }
  /**
   * <code>repeated .identity.proto.SignedCertificate blocked_certs = 5;</code>
   */
  public int getBlockedCertsCount() {
    return blockedCerts_.size();
  }
  /**
   * <code>repeated .identity.proto.SignedCertificate blocked_certs = 5;</code>
   */
  public com.psiphiglobal.identity.proto.SignedCertificate getBlockedCerts(int index) {
    return blockedCerts_.get(index);
  }
  /**
   * <code>repeated .identity.proto.SignedCertificate blocked_certs = 5;</code>
   */
  public com.psiphiglobal.identity.proto.SignedCertificateOrBuilder getBlockedCertsOrBuilder(
      int index) {
    return blockedCerts_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getDomainNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, domainName_);
    }
    if (!getPrimaryCertIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, primaryCertId_);
    }
    for (int i = 0; i < activeCerts_.size(); i++) {
      output.writeMessage(3, activeCerts_.get(i));
    }
    for (int i = 0; i < expiredCerts_.size(); i++) {
      output.writeMessage(4, expiredCerts_.get(i));
    }
    for (int i = 0; i < blockedCerts_.size(); i++) {
      output.writeMessage(5, blockedCerts_.get(i));
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getDomainNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, domainName_);
    }
    if (!getPrimaryCertIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, primaryCertId_);
    }
    for (int i = 0; i < activeCerts_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, activeCerts_.get(i));
    }
    for (int i = 0; i < expiredCerts_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, expiredCerts_.get(i));
    }
    for (int i = 0; i < blockedCerts_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, blockedCerts_.get(i));
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.psiphiglobal.identity.proto.Organization)) {
      return super.equals(obj);
    }
    com.psiphiglobal.identity.proto.Organization other = (com.psiphiglobal.identity.proto.Organization) obj;

    boolean result = true;
    result = result && getDomainName()
        .equals(other.getDomainName());
    result = result && getPrimaryCertId()
        .equals(other.getPrimaryCertId());
    result = result && getActiveCertsList()
        .equals(other.getActiveCertsList());
    result = result && getExpiredCertsList()
        .equals(other.getExpiredCertsList());
    result = result && getBlockedCertsList()
        .equals(other.getBlockedCertsList());
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + DOMAIN_NAME_FIELD_NUMBER;
    hash = (53 * hash) + getDomainName().hashCode();
    hash = (37 * hash) + PRIMARY_CERT_ID_FIELD_NUMBER;
    hash = (53 * hash) + getPrimaryCertId().hashCode();
    if (getActiveCertsCount() > 0) {
      hash = (37 * hash) + ACTIVE_CERTS_FIELD_NUMBER;
      hash = (53 * hash) + getActiveCertsList().hashCode();
    }
    if (getExpiredCertsCount() > 0) {
      hash = (37 * hash) + EXPIRED_CERTS_FIELD_NUMBER;
      hash = (53 * hash) + getExpiredCertsList().hashCode();
    }
    if (getBlockedCertsCount() > 0) {
      hash = (37 * hash) + BLOCKED_CERTS_FIELD_NUMBER;
      hash = (53 * hash) + getBlockedCertsList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.psiphiglobal.identity.proto.Organization parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.psiphiglobal.identity.proto.Organization parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.psiphiglobal.identity.proto.Organization parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.psiphiglobal.identity.proto.Organization parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.psiphiglobal.identity.proto.Organization parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.psiphiglobal.identity.proto.Organization parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.psiphiglobal.identity.proto.Organization parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.psiphiglobal.identity.proto.Organization parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.psiphiglobal.identity.proto.Organization parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.psiphiglobal.identity.proto.Organization parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.psiphiglobal.identity.proto.Organization prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code identity.proto.Organization}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:identity.proto.Organization)
      com.psiphiglobal.identity.proto.OrganizationOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.psiphiglobal.identity.proto.OrganizationOuterClass.internal_static_identity_proto_Organization_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.psiphiglobal.identity.proto.OrganizationOuterClass.internal_static_identity_proto_Organization_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.psiphiglobal.identity.proto.Organization.class, com.psiphiglobal.identity.proto.Organization.Builder.class);
    }

    // Construct using com.psiphiglobal.identity.proto.Organization.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getActiveCertsFieldBuilder();
        getExpiredCertsFieldBuilder();
        getBlockedCertsFieldBuilder();
      }
    }
    public Builder clear() {
      super.clear();
      domainName_ = "";

      primaryCertId_ = "";

      if (activeCertsBuilder_ == null) {
        activeCerts_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
      } else {
        activeCertsBuilder_.clear();
      }
      if (expiredCertsBuilder_ == null) {
        expiredCerts_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000008);
      } else {
        expiredCertsBuilder_.clear();
      }
      if (blockedCertsBuilder_ == null) {
        blockedCerts_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000010);
      } else {
        blockedCertsBuilder_.clear();
      }
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.psiphiglobal.identity.proto.OrganizationOuterClass.internal_static_identity_proto_Organization_descriptor;
    }

    public com.psiphiglobal.identity.proto.Organization getDefaultInstanceForType() {
      return com.psiphiglobal.identity.proto.Organization.getDefaultInstance();
    }

    public com.psiphiglobal.identity.proto.Organization build() {
      com.psiphiglobal.identity.proto.Organization result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.psiphiglobal.identity.proto.Organization buildPartial() {
      com.psiphiglobal.identity.proto.Organization result = new com.psiphiglobal.identity.proto.Organization(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      result.domainName_ = domainName_;
      result.primaryCertId_ = primaryCertId_;
      if (activeCertsBuilder_ == null) {
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          activeCerts_ = java.util.Collections.unmodifiableList(activeCerts_);
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.activeCerts_ = activeCerts_;
      } else {
        result.activeCerts_ = activeCertsBuilder_.build();
      }
      if (expiredCertsBuilder_ == null) {
        if (((bitField0_ & 0x00000008) == 0x00000008)) {
          expiredCerts_ = java.util.Collections.unmodifiableList(expiredCerts_);
          bitField0_ = (bitField0_ & ~0x00000008);
        }
        result.expiredCerts_ = expiredCerts_;
      } else {
        result.expiredCerts_ = expiredCertsBuilder_.build();
      }
      if (blockedCertsBuilder_ == null) {
        if (((bitField0_ & 0x00000010) == 0x00000010)) {
          blockedCerts_ = java.util.Collections.unmodifiableList(blockedCerts_);
          bitField0_ = (bitField0_ & ~0x00000010);
        }
        result.blockedCerts_ = blockedCerts_;
      } else {
        result.blockedCerts_ = blockedCertsBuilder_.build();
      }
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.psiphiglobal.identity.proto.Organization) {
        return mergeFrom((com.psiphiglobal.identity.proto.Organization)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.psiphiglobal.identity.proto.Organization other) {
      if (other == com.psiphiglobal.identity.proto.Organization.getDefaultInstance()) return this;
      if (!other.getDomainName().isEmpty()) {
        domainName_ = other.domainName_;
        onChanged();
      }
      if (!other.getPrimaryCertId().isEmpty()) {
        primaryCertId_ = other.primaryCertId_;
        onChanged();
      }
      if (activeCertsBuilder_ == null) {
        if (!other.activeCerts_.isEmpty()) {
          if (activeCerts_.isEmpty()) {
            activeCerts_ = other.activeCerts_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensureActiveCertsIsMutable();
            activeCerts_.addAll(other.activeCerts_);
          }
          onChanged();
        }
      } else {
        if (!other.activeCerts_.isEmpty()) {
          if (activeCertsBuilder_.isEmpty()) {
            activeCertsBuilder_.dispose();
            activeCertsBuilder_ = null;
            activeCerts_ = other.activeCerts_;
            bitField0_ = (bitField0_ & ~0x00000004);
            activeCertsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getActiveCertsFieldBuilder() : null;
          } else {
            activeCertsBuilder_.addAllMessages(other.activeCerts_);
          }
        }
      }
      if (expiredCertsBuilder_ == null) {
        if (!other.expiredCerts_.isEmpty()) {
          if (expiredCerts_.isEmpty()) {
            expiredCerts_ = other.expiredCerts_;
            bitField0_ = (bitField0_ & ~0x00000008);
          } else {
            ensureExpiredCertsIsMutable();
            expiredCerts_.addAll(other.expiredCerts_);
          }
          onChanged();
        }
      } else {
        if (!other.expiredCerts_.isEmpty()) {
          if (expiredCertsBuilder_.isEmpty()) {
            expiredCertsBuilder_.dispose();
            expiredCertsBuilder_ = null;
            expiredCerts_ = other.expiredCerts_;
            bitField0_ = (bitField0_ & ~0x00000008);
            expiredCertsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getExpiredCertsFieldBuilder() : null;
          } else {
            expiredCertsBuilder_.addAllMessages(other.expiredCerts_);
          }
        }
      }
      if (blockedCertsBuilder_ == null) {
        if (!other.blockedCerts_.isEmpty()) {
          if (blockedCerts_.isEmpty()) {
            blockedCerts_ = other.blockedCerts_;
            bitField0_ = (bitField0_ & ~0x00000010);
          } else {
            ensureBlockedCertsIsMutable();
            blockedCerts_.addAll(other.blockedCerts_);
          }
          onChanged();
        }
      } else {
        if (!other.blockedCerts_.isEmpty()) {
          if (blockedCertsBuilder_.isEmpty()) {
            blockedCertsBuilder_.dispose();
            blockedCertsBuilder_ = null;
            blockedCerts_ = other.blockedCerts_;
            bitField0_ = (bitField0_ & ~0x00000010);
            blockedCertsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getBlockedCertsFieldBuilder() : null;
          } else {
            blockedCertsBuilder_.addAllMessages(other.blockedCerts_);
          }
        }
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.psiphiglobal.identity.proto.Organization parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.psiphiglobal.identity.proto.Organization) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.lang.Object domainName_ = "";
    /**
     * <code>string domain_name = 1;</code>
     */
    public java.lang.String getDomainName() {
      java.lang.Object ref = domainName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        domainName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string domain_name = 1;</code>
     */
    public com.google.protobuf.ByteString
        getDomainNameBytes() {
      java.lang.Object ref = domainName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        domainName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string domain_name = 1;</code>
     */
    public Builder setDomainName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      domainName_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string domain_name = 1;</code>
     */
    public Builder clearDomainName() {
      
      domainName_ = getDefaultInstance().getDomainName();
      onChanged();
      return this;
    }
    /**
     * <code>string domain_name = 1;</code>
     */
    public Builder setDomainNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      domainName_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object primaryCertId_ = "";
    /**
     * <code>string primary_cert_id = 2;</code>
     */
    public java.lang.String getPrimaryCertId() {
      java.lang.Object ref = primaryCertId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        primaryCertId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string primary_cert_id = 2;</code>
     */
    public com.google.protobuf.ByteString
        getPrimaryCertIdBytes() {
      java.lang.Object ref = primaryCertId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        primaryCertId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string primary_cert_id = 2;</code>
     */
    public Builder setPrimaryCertId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      primaryCertId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string primary_cert_id = 2;</code>
     */
    public Builder clearPrimaryCertId() {
      
      primaryCertId_ = getDefaultInstance().getPrimaryCertId();
      onChanged();
      return this;
    }
    /**
     * <code>string primary_cert_id = 2;</code>
     */
    public Builder setPrimaryCertIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      primaryCertId_ = value;
      onChanged();
      return this;
    }

    private java.util.List<com.psiphiglobal.identity.proto.SignedCertificate> activeCerts_ =
      java.util.Collections.emptyList();
    private void ensureActiveCertsIsMutable() {
      if (!((bitField0_ & 0x00000004) == 0x00000004)) {
        activeCerts_ = new java.util.ArrayList<com.psiphiglobal.identity.proto.SignedCertificate>(activeCerts_);
        bitField0_ |= 0x00000004;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.psiphiglobal.identity.proto.SignedCertificate, com.psiphiglobal.identity.proto.SignedCertificate.Builder, com.psiphiglobal.identity.proto.SignedCertificateOrBuilder> activeCertsBuilder_;

    /**
     * <code>repeated .identity.proto.SignedCertificate active_certs = 3;</code>
     */
    public java.util.List<com.psiphiglobal.identity.proto.SignedCertificate> getActiveCertsList() {
      if (activeCertsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(activeCerts_);
      } else {
        return activeCertsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .identity.proto.SignedCertificate active_certs = 3;</code>
     */
    public int getActiveCertsCount() {
      if (activeCertsBuilder_ == null) {
        return activeCerts_.size();
      } else {
        return activeCertsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .identity.proto.SignedCertificate active_certs = 3;</code>
     */
    public com.psiphiglobal.identity.proto.SignedCertificate getActiveCerts(int index) {
      if (activeCertsBuilder_ == null) {
        return activeCerts_.get(index);
      } else {
        return activeCertsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .identity.proto.SignedCertificate active_certs = 3;</code>
     */
    public Builder setActiveCerts(
        int index, com.psiphiglobal.identity.proto.SignedCertificate value) {
      if (activeCertsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureActiveCertsIsMutable();
        activeCerts_.set(index, value);
        onChanged();
      } else {
        activeCertsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .identity.proto.SignedCertificate active_certs = 3;</code>
     */
    public Builder setActiveCerts(
        int index, com.psiphiglobal.identity.proto.SignedCertificate.Builder builderForValue) {
      if (activeCertsBuilder_ == null) {
        ensureActiveCertsIsMutable();
        activeCerts_.set(index, builderForValue.build());
        onChanged();
      } else {
        activeCertsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .identity.proto.SignedCertificate active_certs = 3;</code>
     */
    public Builder addActiveCerts(com.psiphiglobal.identity.proto.SignedCertificate value) {
      if (activeCertsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureActiveCertsIsMutable();
        activeCerts_.add(value);
        onChanged();
      } else {
        activeCertsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .identity.proto.SignedCertificate active_certs = 3;</code>
     */
    public Builder addActiveCerts(
        int index, com.psiphiglobal.identity.proto.SignedCertificate value) {
      if (activeCertsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureActiveCertsIsMutable();
        activeCerts_.add(index, value);
        onChanged();
      } else {
        activeCertsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .identity.proto.SignedCertificate active_certs = 3;</code>
     */
    public Builder addActiveCerts(
        com.psiphiglobal.identity.proto.SignedCertificate.Builder builderForValue) {
      if (activeCertsBuilder_ == null) {
        ensureActiveCertsIsMutable();
        activeCerts_.add(builderForValue.build());
        onChanged();
      } else {
        activeCertsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .identity.proto.SignedCertificate active_certs = 3;</code>
     */
    public Builder addActiveCerts(
        int index, com.psiphiglobal.identity.proto.SignedCertificate.Builder builderForValue) {
      if (activeCertsBuilder_ == null) {
        ensureActiveCertsIsMutable();
        activeCerts_.add(index, builderForValue.build());
        onChanged();
      } else {
        activeCertsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .identity.proto.SignedCertificate active_certs = 3;</code>
     */
    public Builder addAllActiveCerts(
        java.lang.Iterable<? extends com.psiphiglobal.identity.proto.SignedCertificate> values) {
      if (activeCertsBuilder_ == null) {
        ensureActiveCertsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, activeCerts_);
        onChanged();
      } else {
        activeCertsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .identity.proto.SignedCertificate active_certs = 3;</code>
     */
    public Builder clearActiveCerts() {
      if (activeCertsBuilder_ == null) {
        activeCerts_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
      } else {
        activeCertsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .identity.proto.SignedCertificate active_certs = 3;</code>
     */
    public Builder removeActiveCerts(int index) {
      if (activeCertsBuilder_ == null) {
        ensureActiveCertsIsMutable();
        activeCerts_.remove(index);
        onChanged();
      } else {
        activeCertsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .identity.proto.SignedCertificate active_certs = 3;</code>
     */
    public com.psiphiglobal.identity.proto.SignedCertificate.Builder getActiveCertsBuilder(
        int index) {
      return getActiveCertsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .identity.proto.SignedCertificate active_certs = 3;</code>
     */
    public com.psiphiglobal.identity.proto.SignedCertificateOrBuilder getActiveCertsOrBuilder(
        int index) {
      if (activeCertsBuilder_ == null) {
        return activeCerts_.get(index);  } else {
        return activeCertsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .identity.proto.SignedCertificate active_certs = 3;</code>
     */
    public java.util.List<? extends com.psiphiglobal.identity.proto.SignedCertificateOrBuilder> 
         getActiveCertsOrBuilderList() {
      if (activeCertsBuilder_ != null) {
        return activeCertsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(activeCerts_);
      }
    }
    /**
     * <code>repeated .identity.proto.SignedCertificate active_certs = 3;</code>
     */
    public com.psiphiglobal.identity.proto.SignedCertificate.Builder addActiveCertsBuilder() {
      return getActiveCertsFieldBuilder().addBuilder(
          com.psiphiglobal.identity.proto.SignedCertificate.getDefaultInstance());
    }
    /**
     * <code>repeated .identity.proto.SignedCertificate active_certs = 3;</code>
     */
    public com.psiphiglobal.identity.proto.SignedCertificate.Builder addActiveCertsBuilder(
        int index) {
      return getActiveCertsFieldBuilder().addBuilder(
          index, com.psiphiglobal.identity.proto.SignedCertificate.getDefaultInstance());
    }
    /**
     * <code>repeated .identity.proto.SignedCertificate active_certs = 3;</code>
     */
    public java.util.List<com.psiphiglobal.identity.proto.SignedCertificate.Builder> 
         getActiveCertsBuilderList() {
      return getActiveCertsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.psiphiglobal.identity.proto.SignedCertificate, com.psiphiglobal.identity.proto.SignedCertificate.Builder, com.psiphiglobal.identity.proto.SignedCertificateOrBuilder> 
        getActiveCertsFieldBuilder() {
      if (activeCertsBuilder_ == null) {
        activeCertsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.psiphiglobal.identity.proto.SignedCertificate, com.psiphiglobal.identity.proto.SignedCertificate.Builder, com.psiphiglobal.identity.proto.SignedCertificateOrBuilder>(
                activeCerts_,
                ((bitField0_ & 0x00000004) == 0x00000004),
                getParentForChildren(),
                isClean());
        activeCerts_ = null;
      }
      return activeCertsBuilder_;
    }

    private java.util.List<com.psiphiglobal.identity.proto.SignedCertificate> expiredCerts_ =
      java.util.Collections.emptyList();
    private void ensureExpiredCertsIsMutable() {
      if (!((bitField0_ & 0x00000008) == 0x00000008)) {
        expiredCerts_ = new java.util.ArrayList<com.psiphiglobal.identity.proto.SignedCertificate>(expiredCerts_);
        bitField0_ |= 0x00000008;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.psiphiglobal.identity.proto.SignedCertificate, com.psiphiglobal.identity.proto.SignedCertificate.Builder, com.psiphiglobal.identity.proto.SignedCertificateOrBuilder> expiredCertsBuilder_;

    /**
     * <code>repeated .identity.proto.SignedCertificate expired_certs = 4;</code>
     */
    public java.util.List<com.psiphiglobal.identity.proto.SignedCertificate> getExpiredCertsList() {
      if (expiredCertsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(expiredCerts_);
      } else {
        return expiredCertsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .identity.proto.SignedCertificate expired_certs = 4;</code>
     */
    public int getExpiredCertsCount() {
      if (expiredCertsBuilder_ == null) {
        return expiredCerts_.size();
      } else {
        return expiredCertsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .identity.proto.SignedCertificate expired_certs = 4;</code>
     */
    public com.psiphiglobal.identity.proto.SignedCertificate getExpiredCerts(int index) {
      if (expiredCertsBuilder_ == null) {
        return expiredCerts_.get(index);
      } else {
        return expiredCertsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .identity.proto.SignedCertificate expired_certs = 4;</code>
     */
    public Builder setExpiredCerts(
        int index, com.psiphiglobal.identity.proto.SignedCertificate value) {
      if (expiredCertsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureExpiredCertsIsMutable();
        expiredCerts_.set(index, value);
        onChanged();
      } else {
        expiredCertsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .identity.proto.SignedCertificate expired_certs = 4;</code>
     */
    public Builder setExpiredCerts(
        int index, com.psiphiglobal.identity.proto.SignedCertificate.Builder builderForValue) {
      if (expiredCertsBuilder_ == null) {
        ensureExpiredCertsIsMutable();
        expiredCerts_.set(index, builderForValue.build());
        onChanged();
      } else {
        expiredCertsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .identity.proto.SignedCertificate expired_certs = 4;</code>
     */
    public Builder addExpiredCerts(com.psiphiglobal.identity.proto.SignedCertificate value) {
      if (expiredCertsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureExpiredCertsIsMutable();
        expiredCerts_.add(value);
        onChanged();
      } else {
        expiredCertsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .identity.proto.SignedCertificate expired_certs = 4;</code>
     */
    public Builder addExpiredCerts(
        int index, com.psiphiglobal.identity.proto.SignedCertificate value) {
      if (expiredCertsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureExpiredCertsIsMutable();
        expiredCerts_.add(index, value);
        onChanged();
      } else {
        expiredCertsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .identity.proto.SignedCertificate expired_certs = 4;</code>
     */
    public Builder addExpiredCerts(
        com.psiphiglobal.identity.proto.SignedCertificate.Builder builderForValue) {
      if (expiredCertsBuilder_ == null) {
        ensureExpiredCertsIsMutable();
        expiredCerts_.add(builderForValue.build());
        onChanged();
      } else {
        expiredCertsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .identity.proto.SignedCertificate expired_certs = 4;</code>
     */
    public Builder addExpiredCerts(
        int index, com.psiphiglobal.identity.proto.SignedCertificate.Builder builderForValue) {
      if (expiredCertsBuilder_ == null) {
        ensureExpiredCertsIsMutable();
        expiredCerts_.add(index, builderForValue.build());
        onChanged();
      } else {
        expiredCertsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .identity.proto.SignedCertificate expired_certs = 4;</code>
     */
    public Builder addAllExpiredCerts(
        java.lang.Iterable<? extends com.psiphiglobal.identity.proto.SignedCertificate> values) {
      if (expiredCertsBuilder_ == null) {
        ensureExpiredCertsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, expiredCerts_);
        onChanged();
      } else {
        expiredCertsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .identity.proto.SignedCertificate expired_certs = 4;</code>
     */
    public Builder clearExpiredCerts() {
      if (expiredCertsBuilder_ == null) {
        expiredCerts_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
      } else {
        expiredCertsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .identity.proto.SignedCertificate expired_certs = 4;</code>
     */
    public Builder removeExpiredCerts(int index) {
      if (expiredCertsBuilder_ == null) {
        ensureExpiredCertsIsMutable();
        expiredCerts_.remove(index);
        onChanged();
      } else {
        expiredCertsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .identity.proto.SignedCertificate expired_certs = 4;</code>
     */
    public com.psiphiglobal.identity.proto.SignedCertificate.Builder getExpiredCertsBuilder(
        int index) {
      return getExpiredCertsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .identity.proto.SignedCertificate expired_certs = 4;</code>
     */
    public com.psiphiglobal.identity.proto.SignedCertificateOrBuilder getExpiredCertsOrBuilder(
        int index) {
      if (expiredCertsBuilder_ == null) {
        return expiredCerts_.get(index);  } else {
        return expiredCertsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .identity.proto.SignedCertificate expired_certs = 4;</code>
     */
    public java.util.List<? extends com.psiphiglobal.identity.proto.SignedCertificateOrBuilder> 
         getExpiredCertsOrBuilderList() {
      if (expiredCertsBuilder_ != null) {
        return expiredCertsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(expiredCerts_);
      }
    }
    /**
     * <code>repeated .identity.proto.SignedCertificate expired_certs = 4;</code>
     */
    public com.psiphiglobal.identity.proto.SignedCertificate.Builder addExpiredCertsBuilder() {
      return getExpiredCertsFieldBuilder().addBuilder(
          com.psiphiglobal.identity.proto.SignedCertificate.getDefaultInstance());
    }
    /**
     * <code>repeated .identity.proto.SignedCertificate expired_certs = 4;</code>
     */
    public com.psiphiglobal.identity.proto.SignedCertificate.Builder addExpiredCertsBuilder(
        int index) {
      return getExpiredCertsFieldBuilder().addBuilder(
          index, com.psiphiglobal.identity.proto.SignedCertificate.getDefaultInstance());
    }
    /**
     * <code>repeated .identity.proto.SignedCertificate expired_certs = 4;</code>
     */
    public java.util.List<com.psiphiglobal.identity.proto.SignedCertificate.Builder> 
         getExpiredCertsBuilderList() {
      return getExpiredCertsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.psiphiglobal.identity.proto.SignedCertificate, com.psiphiglobal.identity.proto.SignedCertificate.Builder, com.psiphiglobal.identity.proto.SignedCertificateOrBuilder> 
        getExpiredCertsFieldBuilder() {
      if (expiredCertsBuilder_ == null) {
        expiredCertsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.psiphiglobal.identity.proto.SignedCertificate, com.psiphiglobal.identity.proto.SignedCertificate.Builder, com.psiphiglobal.identity.proto.SignedCertificateOrBuilder>(
                expiredCerts_,
                ((bitField0_ & 0x00000008) == 0x00000008),
                getParentForChildren(),
                isClean());
        expiredCerts_ = null;
      }
      return expiredCertsBuilder_;
    }

    private java.util.List<com.psiphiglobal.identity.proto.SignedCertificate> blockedCerts_ =
      java.util.Collections.emptyList();
    private void ensureBlockedCertsIsMutable() {
      if (!((bitField0_ & 0x00000010) == 0x00000010)) {
        blockedCerts_ = new java.util.ArrayList<com.psiphiglobal.identity.proto.SignedCertificate>(blockedCerts_);
        bitField0_ |= 0x00000010;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.psiphiglobal.identity.proto.SignedCertificate, com.psiphiglobal.identity.proto.SignedCertificate.Builder, com.psiphiglobal.identity.proto.SignedCertificateOrBuilder> blockedCertsBuilder_;

    /**
     * <code>repeated .identity.proto.SignedCertificate blocked_certs = 5;</code>
     */
    public java.util.List<com.psiphiglobal.identity.proto.SignedCertificate> getBlockedCertsList() {
      if (blockedCertsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(blockedCerts_);
      } else {
        return blockedCertsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .identity.proto.SignedCertificate blocked_certs = 5;</code>
     */
    public int getBlockedCertsCount() {
      if (blockedCertsBuilder_ == null) {
        return blockedCerts_.size();
      } else {
        return blockedCertsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .identity.proto.SignedCertificate blocked_certs = 5;</code>
     */
    public com.psiphiglobal.identity.proto.SignedCertificate getBlockedCerts(int index) {
      if (blockedCertsBuilder_ == null) {
        return blockedCerts_.get(index);
      } else {
        return blockedCertsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .identity.proto.SignedCertificate blocked_certs = 5;</code>
     */
    public Builder setBlockedCerts(
        int index, com.psiphiglobal.identity.proto.SignedCertificate value) {
      if (blockedCertsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureBlockedCertsIsMutable();
        blockedCerts_.set(index, value);
        onChanged();
      } else {
        blockedCertsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .identity.proto.SignedCertificate blocked_certs = 5;</code>
     */
    public Builder setBlockedCerts(
        int index, com.psiphiglobal.identity.proto.SignedCertificate.Builder builderForValue) {
      if (blockedCertsBuilder_ == null) {
        ensureBlockedCertsIsMutable();
        blockedCerts_.set(index, builderForValue.build());
        onChanged();
      } else {
        blockedCertsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .identity.proto.SignedCertificate blocked_certs = 5;</code>
     */
    public Builder addBlockedCerts(com.psiphiglobal.identity.proto.SignedCertificate value) {
      if (blockedCertsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureBlockedCertsIsMutable();
        blockedCerts_.add(value);
        onChanged();
      } else {
        blockedCertsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .identity.proto.SignedCertificate blocked_certs = 5;</code>
     */
    public Builder addBlockedCerts(
        int index, com.psiphiglobal.identity.proto.SignedCertificate value) {
      if (blockedCertsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureBlockedCertsIsMutable();
        blockedCerts_.add(index, value);
        onChanged();
      } else {
        blockedCertsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .identity.proto.SignedCertificate blocked_certs = 5;</code>
     */
    public Builder addBlockedCerts(
        com.psiphiglobal.identity.proto.SignedCertificate.Builder builderForValue) {
      if (blockedCertsBuilder_ == null) {
        ensureBlockedCertsIsMutable();
        blockedCerts_.add(builderForValue.build());
        onChanged();
      } else {
        blockedCertsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .identity.proto.SignedCertificate blocked_certs = 5;</code>
     */
    public Builder addBlockedCerts(
        int index, com.psiphiglobal.identity.proto.SignedCertificate.Builder builderForValue) {
      if (blockedCertsBuilder_ == null) {
        ensureBlockedCertsIsMutable();
        blockedCerts_.add(index, builderForValue.build());
        onChanged();
      } else {
        blockedCertsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .identity.proto.SignedCertificate blocked_certs = 5;</code>
     */
    public Builder addAllBlockedCerts(
        java.lang.Iterable<? extends com.psiphiglobal.identity.proto.SignedCertificate> values) {
      if (blockedCertsBuilder_ == null) {
        ensureBlockedCertsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, blockedCerts_);
        onChanged();
      } else {
        blockedCertsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .identity.proto.SignedCertificate blocked_certs = 5;</code>
     */
    public Builder clearBlockedCerts() {
      if (blockedCertsBuilder_ == null) {
        blockedCerts_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000010);
        onChanged();
      } else {
        blockedCertsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .identity.proto.SignedCertificate blocked_certs = 5;</code>
     */
    public Builder removeBlockedCerts(int index) {
      if (blockedCertsBuilder_ == null) {
        ensureBlockedCertsIsMutable();
        blockedCerts_.remove(index);
        onChanged();
      } else {
        blockedCertsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .identity.proto.SignedCertificate blocked_certs = 5;</code>
     */
    public com.psiphiglobal.identity.proto.SignedCertificate.Builder getBlockedCertsBuilder(
        int index) {
      return getBlockedCertsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .identity.proto.SignedCertificate blocked_certs = 5;</code>
     */
    public com.psiphiglobal.identity.proto.SignedCertificateOrBuilder getBlockedCertsOrBuilder(
        int index) {
      if (blockedCertsBuilder_ == null) {
        return blockedCerts_.get(index);  } else {
        return blockedCertsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .identity.proto.SignedCertificate blocked_certs = 5;</code>
     */
    public java.util.List<? extends com.psiphiglobal.identity.proto.SignedCertificateOrBuilder> 
         getBlockedCertsOrBuilderList() {
      if (blockedCertsBuilder_ != null) {
        return blockedCertsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(blockedCerts_);
      }
    }
    /**
     * <code>repeated .identity.proto.SignedCertificate blocked_certs = 5;</code>
     */
    public com.psiphiglobal.identity.proto.SignedCertificate.Builder addBlockedCertsBuilder() {
      return getBlockedCertsFieldBuilder().addBuilder(
          com.psiphiglobal.identity.proto.SignedCertificate.getDefaultInstance());
    }
    /**
     * <code>repeated .identity.proto.SignedCertificate blocked_certs = 5;</code>
     */
    public com.psiphiglobal.identity.proto.SignedCertificate.Builder addBlockedCertsBuilder(
        int index) {
      return getBlockedCertsFieldBuilder().addBuilder(
          index, com.psiphiglobal.identity.proto.SignedCertificate.getDefaultInstance());
    }
    /**
     * <code>repeated .identity.proto.SignedCertificate blocked_certs = 5;</code>
     */
    public java.util.List<com.psiphiglobal.identity.proto.SignedCertificate.Builder> 
         getBlockedCertsBuilderList() {
      return getBlockedCertsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.psiphiglobal.identity.proto.SignedCertificate, com.psiphiglobal.identity.proto.SignedCertificate.Builder, com.psiphiglobal.identity.proto.SignedCertificateOrBuilder> 
        getBlockedCertsFieldBuilder() {
      if (blockedCertsBuilder_ == null) {
        blockedCertsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.psiphiglobal.identity.proto.SignedCertificate, com.psiphiglobal.identity.proto.SignedCertificate.Builder, com.psiphiglobal.identity.proto.SignedCertificateOrBuilder>(
                blockedCerts_,
                ((bitField0_ & 0x00000010) == 0x00000010),
                getParentForChildren(),
                isClean());
        blockedCerts_ = null;
      }
      return blockedCertsBuilder_;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:identity.proto.Organization)
  }

  // @@protoc_insertion_point(class_scope:identity.proto.Organization)
  private static final com.psiphiglobal.identity.proto.Organization DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.psiphiglobal.identity.proto.Organization();
  }

  public static com.psiphiglobal.identity.proto.Organization getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Organization>
      PARSER = new com.google.protobuf.AbstractParser<Organization>() {
    public Organization parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new Organization(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Organization> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Organization> getParserForType() {
    return PARSER;
  }

  public com.psiphiglobal.identity.proto.Organization getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

