// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: organization.proto

package com.psiphiglobal.identity.proto;

public interface OrganizationOrBuilder extends
    // @@protoc_insertion_point(interface_extends:identity.proto.Organization)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string domain_name = 1;</code>
   */
  java.lang.String getDomainName();
  /**
   * <code>string domain_name = 1;</code>
   */
  com.google.protobuf.ByteString
      getDomainNameBytes();

  /**
   * <code>string primary_cert_id = 2;</code>
   */
  java.lang.String getPrimaryCertId();
  /**
   * <code>string primary_cert_id = 2;</code>
   */
  com.google.protobuf.ByteString
      getPrimaryCertIdBytes();

  /**
   * <code>repeated .identity.proto.SignedCertificate active_certs = 3;</code>
   */
  java.util.List<com.psiphiglobal.identity.proto.SignedCertificate> 
      getActiveCertsList();
  /**
   * <code>repeated .identity.proto.SignedCertificate active_certs = 3;</code>
   */
  com.psiphiglobal.identity.proto.SignedCertificate getActiveCerts(int index);
  /**
   * <code>repeated .identity.proto.SignedCertificate active_certs = 3;</code>
   */
  int getActiveCertsCount();
  /**
   * <code>repeated .identity.proto.SignedCertificate active_certs = 3;</code>
   */
  java.util.List<? extends com.psiphiglobal.identity.proto.SignedCertificateOrBuilder> 
      getActiveCertsOrBuilderList();
  /**
   * <code>repeated .identity.proto.SignedCertificate active_certs = 3;</code>
   */
  com.psiphiglobal.identity.proto.SignedCertificateOrBuilder getActiveCertsOrBuilder(
      int index);

  /**
   * <code>repeated .identity.proto.SignedCertificate expired_certs = 4;</code>
   */
  java.util.List<com.psiphiglobal.identity.proto.SignedCertificate> 
      getExpiredCertsList();
  /**
   * <code>repeated .identity.proto.SignedCertificate expired_certs = 4;</code>
   */
  com.psiphiglobal.identity.proto.SignedCertificate getExpiredCerts(int index);
  /**
   * <code>repeated .identity.proto.SignedCertificate expired_certs = 4;</code>
   */
  int getExpiredCertsCount();
  /**
   * <code>repeated .identity.proto.SignedCertificate expired_certs = 4;</code>
   */
  java.util.List<? extends com.psiphiglobal.identity.proto.SignedCertificateOrBuilder> 
      getExpiredCertsOrBuilderList();
  /**
   * <code>repeated .identity.proto.SignedCertificate expired_certs = 4;</code>
   */
  com.psiphiglobal.identity.proto.SignedCertificateOrBuilder getExpiredCertsOrBuilder(
      int index);

  /**
   * <code>repeated .identity.proto.SignedCertificate blocked_certs = 5;</code>
   */
  java.util.List<com.psiphiglobal.identity.proto.SignedCertificate> 
      getBlockedCertsList();
  /**
   * <code>repeated .identity.proto.SignedCertificate blocked_certs = 5;</code>
   */
  com.psiphiglobal.identity.proto.SignedCertificate getBlockedCerts(int index);
  /**
   * <code>repeated .identity.proto.SignedCertificate blocked_certs = 5;</code>
   */
  int getBlockedCertsCount();
  /**
   * <code>repeated .identity.proto.SignedCertificate blocked_certs = 5;</code>
   */
  java.util.List<? extends com.psiphiglobal.identity.proto.SignedCertificateOrBuilder> 
      getBlockedCertsOrBuilderList();
  /**
   * <code>repeated .identity.proto.SignedCertificate blocked_certs = 5;</code>
   */
  com.psiphiglobal.identity.proto.SignedCertificateOrBuilder getBlockedCertsOrBuilder(
      int index);
}
