// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: organization.proto

package com.psiphiglobal.identity.proto;

/**
 * Protobuf enum {@code identity.proto.Role}
 */
public enum Role
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>CUSTOMER = 0;</code>
   */
  CUSTOMER(0),
  /**
   * <code>ADMIN = 1;</code>
   */
  ADMIN(1),
  /**
   * <code>TEAM_LEAD = 2;</code>
   */
  TEAM_LEAD(2),
  /**
   * <code>KYC_ANALYST = 3;</code>
   */
  KYC_ANALYST(3),
  /**
   * <code>COMPLIANCE_OFFICER = 4;</code>
   */
  COMPLIANCE_OFFICER(4),
  /**
   * <code>AUDITOR = 5;</code>
   */
  AUDITOR(5),
  /**
   * <code>REQUESTING_BANK = 6;</code>
   */
  REQUESTING_BANK(6),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>CUSTOMER = 0;</code>
   */
  public static final int CUSTOMER_VALUE = 0;
  /**
   * <code>ADMIN = 1;</code>
   */
  public static final int ADMIN_VALUE = 1;
  /**
   * <code>TEAM_LEAD = 2;</code>
   */
  public static final int TEAM_LEAD_VALUE = 2;
  /**
   * <code>KYC_ANALYST = 3;</code>
   */
  public static final int KYC_ANALYST_VALUE = 3;
  /**
   * <code>COMPLIANCE_OFFICER = 4;</code>
   */
  public static final int COMPLIANCE_OFFICER_VALUE = 4;
  /**
   * <code>AUDITOR = 5;</code>
   */
  public static final int AUDITOR_VALUE = 5;
  /**
   * <code>REQUESTING_BANK = 6;</code>
   */
  public static final int REQUESTING_BANK_VALUE = 6;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static Role valueOf(int value) {
    return forNumber(value);
  }

  public static Role forNumber(int value) {
    switch (value) {
      case 0: return CUSTOMER;
      case 1: return ADMIN;
      case 2: return TEAM_LEAD;
      case 3: return KYC_ANALYST;
      case 4: return COMPLIANCE_OFFICER;
      case 5: return AUDITOR;
      case 6: return REQUESTING_BANK;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<Role>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      Role> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<Role>() {
          public Role findValueByNumber(int number) {
            return Role.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return com.psiphiglobal.identity.proto.OrganizationOuterClass.getDescriptor().getEnumTypes().get(2);
  }

  private static final Role[] VALUES = values();

  public static Role valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private Role(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:identity.proto.Role)
}

