// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: organization.proto

package com.psiphiglobal.identity.proto;

/**
 * Protobuf type {@code identity.proto.SignedCertificate}
 */
public  final class SignedCertificate extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:identity.proto.SignedCertificate)
    SignedCertificateOrBuilder {
  // Use SignedCertificate.newBuilder() to construct.
  private SignedCertificate(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private SignedCertificate() {
    id_ = "";
    status_ = 0;
    createdAt_ = 0L;
    expiredAt_ = 0L;
    autoValidation_ = 0;
    validations_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private SignedCertificate(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            id_ = s;
            break;
          }
          case 16: {
            int rawValue = input.readEnum();

            status_ = rawValue;
            break;
          }
          case 24: {

            createdAt_ = input.readUInt64();
            break;
          }
          case 32: {

            expiredAt_ = input.readUInt64();
            break;
          }
          case 40: {
            int rawValue = input.readEnum();

            autoValidation_ = rawValue;
            break;
          }
          case 50: {
            com.psiphiglobal.identity.proto.CertificateData.Builder subBuilder = null;
            if (data_ != null) {
              subBuilder = data_.toBuilder();
            }
            data_ = input.readMessage(com.psiphiglobal.identity.proto.CertificateData.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(data_);
              data_ = subBuilder.buildPartial();
            }

            break;
          }
          case 58: {
            com.psiphiglobal.identity.proto.Signature.Builder subBuilder = null;
            if (selfSign_ != null) {
              subBuilder = selfSign_.toBuilder();
            }
            selfSign_ = input.readMessage(com.psiphiglobal.identity.proto.Signature.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(selfSign_);
              selfSign_ = subBuilder.buildPartial();
            }

            break;
          }
          case 66: {
            if (!((mutable_bitField0_ & 0x00000080) == 0x00000080)) {
              validations_ = new java.util.ArrayList<com.psiphiglobal.identity.proto.Signature>();
              mutable_bitField0_ |= 0x00000080;
            }
            validations_.add(
                input.readMessage(com.psiphiglobal.identity.proto.Signature.parser(), extensionRegistry));
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000080) == 0x00000080)) {
        validations_ = java.util.Collections.unmodifiableList(validations_);
      }
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.psiphiglobal.identity.proto.OrganizationOuterClass.internal_static_identity_proto_SignedCertificate_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.psiphiglobal.identity.proto.OrganizationOuterClass.internal_static_identity_proto_SignedCertificate_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.psiphiglobal.identity.proto.SignedCertificate.class, com.psiphiglobal.identity.proto.SignedCertificate.Builder.class);
  }

  private int bitField0_;
  public static final int ID_FIELD_NUMBER = 1;
  private volatile java.lang.Object id_;
  /**
   * <code>string id = 1;</code>
   */
  public java.lang.String getId() {
    java.lang.Object ref = id_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      id_ = s;
      return s;
    }
  }
  /**
   * <code>string id = 1;</code>
   */
  public com.google.protobuf.ByteString
      getIdBytes() {
    java.lang.Object ref = id_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      id_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int STATUS_FIELD_NUMBER = 2;
  private int status_;
  /**
   * <code>.identity.proto.CertificateStatus status = 2;</code>
   */
  public int getStatusValue() {
    return status_;
  }
  /**
   * <code>.identity.proto.CertificateStatus status = 2;</code>
   */
  public com.psiphiglobal.identity.proto.CertificateStatus getStatus() {
    com.psiphiglobal.identity.proto.CertificateStatus result = com.psiphiglobal.identity.proto.CertificateStatus.valueOf(status_);
    return result == null ? com.psiphiglobal.identity.proto.CertificateStatus.UNRECOGNIZED : result;
  }

  public static final int CREATED_AT_FIELD_NUMBER = 3;
  private long createdAt_;
  /**
   * <code>uint64 created_at = 3;</code>
   */
  public long getCreatedAt() {
    return createdAt_;
  }

  public static final int EXPIRED_AT_FIELD_NUMBER = 4;
  private long expiredAt_;
  /**
   * <code>uint64 expired_at = 4;</code>
   */
  public long getExpiredAt() {
    return expiredAt_;
  }

  public static final int AUTO_VALIDATION_FIELD_NUMBER = 5;
  private int autoValidation_;
  /**
   * <code>.identity.proto.AutoValidationMechanism auto_validation = 5;</code>
   */
  public int getAutoValidationValue() {
    return autoValidation_;
  }
  /**
   * <code>.identity.proto.AutoValidationMechanism auto_validation = 5;</code>
   */
  public com.psiphiglobal.identity.proto.AutoValidationMechanism getAutoValidation() {
    com.psiphiglobal.identity.proto.AutoValidationMechanism result = com.psiphiglobal.identity.proto.AutoValidationMechanism.valueOf(autoValidation_);
    return result == null ? com.psiphiglobal.identity.proto.AutoValidationMechanism.UNRECOGNIZED : result;
  }

  public static final int DATA_FIELD_NUMBER = 6;
  private com.psiphiglobal.identity.proto.CertificateData data_;
  /**
   * <code>.identity.proto.CertificateData data = 6;</code>
   */
  public boolean hasData() {
    return data_ != null;
  }
  /**
   * <code>.identity.proto.CertificateData data = 6;</code>
   */
  public com.psiphiglobal.identity.proto.CertificateData getData() {
    return data_ == null ? com.psiphiglobal.identity.proto.CertificateData.getDefaultInstance() : data_;
  }
  /**
   * <code>.identity.proto.CertificateData data = 6;</code>
   */
  public com.psiphiglobal.identity.proto.CertificateDataOrBuilder getDataOrBuilder() {
    return getData();
  }

  public static final int SELF_SIGN_FIELD_NUMBER = 7;
  private com.psiphiglobal.identity.proto.Signature selfSign_;
  /**
   * <code>.identity.proto.Signature self_sign = 7;</code>
   */
  public boolean hasSelfSign() {
    return selfSign_ != null;
  }
  /**
   * <code>.identity.proto.Signature self_sign = 7;</code>
   */
  public com.psiphiglobal.identity.proto.Signature getSelfSign() {
    return selfSign_ == null ? com.psiphiglobal.identity.proto.Signature.getDefaultInstance() : selfSign_;
  }
  /**
   * <code>.identity.proto.Signature self_sign = 7;</code>
   */
  public com.psiphiglobal.identity.proto.SignatureOrBuilder getSelfSignOrBuilder() {
    return getSelfSign();
  }

  public static final int VALIDATIONS_FIELD_NUMBER = 8;
  private java.util.List<com.psiphiglobal.identity.proto.Signature> validations_;
  /**
   * <code>repeated .identity.proto.Signature validations = 8;</code>
   */
  public java.util.List<com.psiphiglobal.identity.proto.Signature> getValidationsList() {
    return validations_;
  }
  /**
   * <code>repeated .identity.proto.Signature validations = 8;</code>
   */
  public java.util.List<? extends com.psiphiglobal.identity.proto.SignatureOrBuilder> 
      getValidationsOrBuilderList() {
    return validations_;
  }
  /**
   * <code>repeated .identity.proto.Signature validations = 8;</code>
   */
  public int getValidationsCount() {
    return validations_.size();
  }
  /**
   * <code>repeated .identity.proto.Signature validations = 8;</code>
   */
  public com.psiphiglobal.identity.proto.Signature getValidations(int index) {
    return validations_.get(index);
  }
  /**
   * <code>repeated .identity.proto.Signature validations = 8;</code>
   */
  public com.psiphiglobal.identity.proto.SignatureOrBuilder getValidationsOrBuilder(
      int index) {
    return validations_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, id_);
    }
    if (status_ != com.psiphiglobal.identity.proto.CertificateStatus.ACTIVE.getNumber()) {
      output.writeEnum(2, status_);
    }
    if (createdAt_ != 0L) {
      output.writeUInt64(3, createdAt_);
    }
    if (expiredAt_ != 0L) {
      output.writeUInt64(4, expiredAt_);
    }
    if (autoValidation_ != com.psiphiglobal.identity.proto.AutoValidationMechanism.UNKNOWN.getNumber()) {
      output.writeEnum(5, autoValidation_);
    }
    if (data_ != null) {
      output.writeMessage(6, getData());
    }
    if (selfSign_ != null) {
      output.writeMessage(7, getSelfSign());
    }
    for (int i = 0; i < validations_.size(); i++) {
      output.writeMessage(8, validations_.get(i));
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, id_);
    }
    if (status_ != com.psiphiglobal.identity.proto.CertificateStatus.ACTIVE.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(2, status_);
    }
    if (createdAt_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(3, createdAt_);
    }
    if (expiredAt_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(4, expiredAt_);
    }
    if (autoValidation_ != com.psiphiglobal.identity.proto.AutoValidationMechanism.UNKNOWN.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(5, autoValidation_);
    }
    if (data_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(6, getData());
    }
    if (selfSign_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(7, getSelfSign());
    }
    for (int i = 0; i < validations_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(8, validations_.get(i));
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.psiphiglobal.identity.proto.SignedCertificate)) {
      return super.equals(obj);
    }
    com.psiphiglobal.identity.proto.SignedCertificate other = (com.psiphiglobal.identity.proto.SignedCertificate) obj;

    boolean result = true;
    result = result && getId()
        .equals(other.getId());
    result = result && status_ == other.status_;
    result = result && (getCreatedAt()
        == other.getCreatedAt());
    result = result && (getExpiredAt()
        == other.getExpiredAt());
    result = result && autoValidation_ == other.autoValidation_;
    result = result && (hasData() == other.hasData());
    if (hasData()) {
      result = result && getData()
          .equals(other.getData());
    }
    result = result && (hasSelfSign() == other.hasSelfSign());
    if (hasSelfSign()) {
      result = result && getSelfSign()
          .equals(other.getSelfSign());
    }
    result = result && getValidationsList()
        .equals(other.getValidationsList());
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ID_FIELD_NUMBER;
    hash = (53 * hash) + getId().hashCode();
    hash = (37 * hash) + STATUS_FIELD_NUMBER;
    hash = (53 * hash) + status_;
    hash = (37 * hash) + CREATED_AT_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getCreatedAt());
    hash = (37 * hash) + EXPIRED_AT_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getExpiredAt());
    hash = (37 * hash) + AUTO_VALIDATION_FIELD_NUMBER;
    hash = (53 * hash) + autoValidation_;
    if (hasData()) {
      hash = (37 * hash) + DATA_FIELD_NUMBER;
      hash = (53 * hash) + getData().hashCode();
    }
    if (hasSelfSign()) {
      hash = (37 * hash) + SELF_SIGN_FIELD_NUMBER;
      hash = (53 * hash) + getSelfSign().hashCode();
    }
    if (getValidationsCount() > 0) {
      hash = (37 * hash) + VALIDATIONS_FIELD_NUMBER;
      hash = (53 * hash) + getValidationsList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.psiphiglobal.identity.proto.SignedCertificate parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.psiphiglobal.identity.proto.SignedCertificate parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.psiphiglobal.identity.proto.SignedCertificate parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.psiphiglobal.identity.proto.SignedCertificate parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.psiphiglobal.identity.proto.SignedCertificate parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.psiphiglobal.identity.proto.SignedCertificate parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.psiphiglobal.identity.proto.SignedCertificate parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.psiphiglobal.identity.proto.SignedCertificate parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.psiphiglobal.identity.proto.SignedCertificate parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.psiphiglobal.identity.proto.SignedCertificate parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.psiphiglobal.identity.proto.SignedCertificate prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code identity.proto.SignedCertificate}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:identity.proto.SignedCertificate)
      com.psiphiglobal.identity.proto.SignedCertificateOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.psiphiglobal.identity.proto.OrganizationOuterClass.internal_static_identity_proto_SignedCertificate_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.psiphiglobal.identity.proto.OrganizationOuterClass.internal_static_identity_proto_SignedCertificate_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.psiphiglobal.identity.proto.SignedCertificate.class, com.psiphiglobal.identity.proto.SignedCertificate.Builder.class);
    }

    // Construct using com.psiphiglobal.identity.proto.SignedCertificate.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getValidationsFieldBuilder();
      }
    }
    public Builder clear() {
      super.clear();
      id_ = "";

      status_ = 0;

      createdAt_ = 0L;

      expiredAt_ = 0L;

      autoValidation_ = 0;

      if (dataBuilder_ == null) {
        data_ = null;
      } else {
        data_ = null;
        dataBuilder_ = null;
      }
      if (selfSignBuilder_ == null) {
        selfSign_ = null;
      } else {
        selfSign_ = null;
        selfSignBuilder_ = null;
      }
      if (validationsBuilder_ == null) {
        validations_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000080);
      } else {
        validationsBuilder_.clear();
      }
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.psiphiglobal.identity.proto.OrganizationOuterClass.internal_static_identity_proto_SignedCertificate_descriptor;
    }

    public com.psiphiglobal.identity.proto.SignedCertificate getDefaultInstanceForType() {
      return com.psiphiglobal.identity.proto.SignedCertificate.getDefaultInstance();
    }

    public com.psiphiglobal.identity.proto.SignedCertificate build() {
      com.psiphiglobal.identity.proto.SignedCertificate result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.psiphiglobal.identity.proto.SignedCertificate buildPartial() {
      com.psiphiglobal.identity.proto.SignedCertificate result = new com.psiphiglobal.identity.proto.SignedCertificate(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      result.id_ = id_;
      result.status_ = status_;
      result.createdAt_ = createdAt_;
      result.expiredAt_ = expiredAt_;
      result.autoValidation_ = autoValidation_;
      if (dataBuilder_ == null) {
        result.data_ = data_;
      } else {
        result.data_ = dataBuilder_.build();
      }
      if (selfSignBuilder_ == null) {
        result.selfSign_ = selfSign_;
      } else {
        result.selfSign_ = selfSignBuilder_.build();
      }
      if (validationsBuilder_ == null) {
        if (((bitField0_ & 0x00000080) == 0x00000080)) {
          validations_ = java.util.Collections.unmodifiableList(validations_);
          bitField0_ = (bitField0_ & ~0x00000080);
        }
        result.validations_ = validations_;
      } else {
        result.validations_ = validationsBuilder_.build();
      }
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.psiphiglobal.identity.proto.SignedCertificate) {
        return mergeFrom((com.psiphiglobal.identity.proto.SignedCertificate)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.psiphiglobal.identity.proto.SignedCertificate other) {
      if (other == com.psiphiglobal.identity.proto.SignedCertificate.getDefaultInstance()) return this;
      if (!other.getId().isEmpty()) {
        id_ = other.id_;
        onChanged();
      }
      if (other.status_ != 0) {
        setStatusValue(other.getStatusValue());
      }
      if (other.getCreatedAt() != 0L) {
        setCreatedAt(other.getCreatedAt());
      }
      if (other.getExpiredAt() != 0L) {
        setExpiredAt(other.getExpiredAt());
      }
      if (other.autoValidation_ != 0) {
        setAutoValidationValue(other.getAutoValidationValue());
      }
      if (other.hasData()) {
        mergeData(other.getData());
      }
      if (other.hasSelfSign()) {
        mergeSelfSign(other.getSelfSign());
      }
      if (validationsBuilder_ == null) {
        if (!other.validations_.isEmpty()) {
          if (validations_.isEmpty()) {
            validations_ = other.validations_;
            bitField0_ = (bitField0_ & ~0x00000080);
          } else {
            ensureValidationsIsMutable();
            validations_.addAll(other.validations_);
          }
          onChanged();
        }
      } else {
        if (!other.validations_.isEmpty()) {
          if (validationsBuilder_.isEmpty()) {
            validationsBuilder_.dispose();
            validationsBuilder_ = null;
            validations_ = other.validations_;
            bitField0_ = (bitField0_ & ~0x00000080);
            validationsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getValidationsFieldBuilder() : null;
          } else {
            validationsBuilder_.addAllMessages(other.validations_);
          }
        }
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.psiphiglobal.identity.proto.SignedCertificate parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.psiphiglobal.identity.proto.SignedCertificate) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.lang.Object id_ = "";
    /**
     * <code>string id = 1;</code>
     */
    public java.lang.String getId() {
      java.lang.Object ref = id_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        id_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string id = 1;</code>
     */
    public com.google.protobuf.ByteString
        getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string id = 1;</code>
     */
    public Builder setId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      id_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string id = 1;</code>
     */
    public Builder clearId() {
      
      id_ = getDefaultInstance().getId();
      onChanged();
      return this;
    }
    /**
     * <code>string id = 1;</code>
     */
    public Builder setIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      id_ = value;
      onChanged();
      return this;
    }

    private int status_ = 0;
    /**
     * <code>.identity.proto.CertificateStatus status = 2;</code>
     */
    public int getStatusValue() {
      return status_;
    }
    /**
     * <code>.identity.proto.CertificateStatus status = 2;</code>
     */
    public Builder setStatusValue(int value) {
      status_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.identity.proto.CertificateStatus status = 2;</code>
     */
    public com.psiphiglobal.identity.proto.CertificateStatus getStatus() {
      com.psiphiglobal.identity.proto.CertificateStatus result = com.psiphiglobal.identity.proto.CertificateStatus.valueOf(status_);
      return result == null ? com.psiphiglobal.identity.proto.CertificateStatus.UNRECOGNIZED : result;
    }
    /**
     * <code>.identity.proto.CertificateStatus status = 2;</code>
     */
    public Builder setStatus(com.psiphiglobal.identity.proto.CertificateStatus value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      status_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.identity.proto.CertificateStatus status = 2;</code>
     */
    public Builder clearStatus() {
      
      status_ = 0;
      onChanged();
      return this;
    }

    private long createdAt_ ;
    /**
     * <code>uint64 created_at = 3;</code>
     */
    public long getCreatedAt() {
      return createdAt_;
    }
    /**
     * <code>uint64 created_at = 3;</code>
     */
    public Builder setCreatedAt(long value) {
      
      createdAt_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>uint64 created_at = 3;</code>
     */
    public Builder clearCreatedAt() {
      
      createdAt_ = 0L;
      onChanged();
      return this;
    }

    private long expiredAt_ ;
    /**
     * <code>uint64 expired_at = 4;</code>
     */
    public long getExpiredAt() {
      return expiredAt_;
    }
    /**
     * <code>uint64 expired_at = 4;</code>
     */
    public Builder setExpiredAt(long value) {
      
      expiredAt_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>uint64 expired_at = 4;</code>
     */
    public Builder clearExpiredAt() {
      
      expiredAt_ = 0L;
      onChanged();
      return this;
    }

    private int autoValidation_ = 0;
    /**
     * <code>.identity.proto.AutoValidationMechanism auto_validation = 5;</code>
     */
    public int getAutoValidationValue() {
      return autoValidation_;
    }
    /**
     * <code>.identity.proto.AutoValidationMechanism auto_validation = 5;</code>
     */
    public Builder setAutoValidationValue(int value) {
      autoValidation_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.identity.proto.AutoValidationMechanism auto_validation = 5;</code>
     */
    public com.psiphiglobal.identity.proto.AutoValidationMechanism getAutoValidation() {
      com.psiphiglobal.identity.proto.AutoValidationMechanism result = com.psiphiglobal.identity.proto.AutoValidationMechanism.valueOf(autoValidation_);
      return result == null ? com.psiphiglobal.identity.proto.AutoValidationMechanism.UNRECOGNIZED : result;
    }
    /**
     * <code>.identity.proto.AutoValidationMechanism auto_validation = 5;</code>
     */
    public Builder setAutoValidation(com.psiphiglobal.identity.proto.AutoValidationMechanism value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      autoValidation_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.identity.proto.AutoValidationMechanism auto_validation = 5;</code>
     */
    public Builder clearAutoValidation() {
      
      autoValidation_ = 0;
      onChanged();
      return this;
    }

    private com.psiphiglobal.identity.proto.CertificateData data_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.psiphiglobal.identity.proto.CertificateData, com.psiphiglobal.identity.proto.CertificateData.Builder, com.psiphiglobal.identity.proto.CertificateDataOrBuilder> dataBuilder_;
    /**
     * <code>.identity.proto.CertificateData data = 6;</code>
     */
    public boolean hasData() {
      return dataBuilder_ != null || data_ != null;
    }
    /**
     * <code>.identity.proto.CertificateData data = 6;</code>
     */
    public com.psiphiglobal.identity.proto.CertificateData getData() {
      if (dataBuilder_ == null) {
        return data_ == null ? com.psiphiglobal.identity.proto.CertificateData.getDefaultInstance() : data_;
      } else {
        return dataBuilder_.getMessage();
      }
    }
    /**
     * <code>.identity.proto.CertificateData data = 6;</code>
     */
    public Builder setData(com.psiphiglobal.identity.proto.CertificateData value) {
      if (dataBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        data_ = value;
        onChanged();
      } else {
        dataBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.identity.proto.CertificateData data = 6;</code>
     */
    public Builder setData(
        com.psiphiglobal.identity.proto.CertificateData.Builder builderForValue) {
      if (dataBuilder_ == null) {
        data_ = builderForValue.build();
        onChanged();
      } else {
        dataBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.identity.proto.CertificateData data = 6;</code>
     */
    public Builder mergeData(com.psiphiglobal.identity.proto.CertificateData value) {
      if (dataBuilder_ == null) {
        if (data_ != null) {
          data_ =
            com.psiphiglobal.identity.proto.CertificateData.newBuilder(data_).mergeFrom(value).buildPartial();
        } else {
          data_ = value;
        }
        onChanged();
      } else {
        dataBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.identity.proto.CertificateData data = 6;</code>
     */
    public Builder clearData() {
      if (dataBuilder_ == null) {
        data_ = null;
        onChanged();
      } else {
        data_ = null;
        dataBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.identity.proto.CertificateData data = 6;</code>
     */
    public com.psiphiglobal.identity.proto.CertificateData.Builder getDataBuilder() {
      
      onChanged();
      return getDataFieldBuilder().getBuilder();
    }
    /**
     * <code>.identity.proto.CertificateData data = 6;</code>
     */
    public com.psiphiglobal.identity.proto.CertificateDataOrBuilder getDataOrBuilder() {
      if (dataBuilder_ != null) {
        return dataBuilder_.getMessageOrBuilder();
      } else {
        return data_ == null ?
            com.psiphiglobal.identity.proto.CertificateData.getDefaultInstance() : data_;
      }
    }
    /**
     * <code>.identity.proto.CertificateData data = 6;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.psiphiglobal.identity.proto.CertificateData, com.psiphiglobal.identity.proto.CertificateData.Builder, com.psiphiglobal.identity.proto.CertificateDataOrBuilder> 
        getDataFieldBuilder() {
      if (dataBuilder_ == null) {
        dataBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.psiphiglobal.identity.proto.CertificateData, com.psiphiglobal.identity.proto.CertificateData.Builder, com.psiphiglobal.identity.proto.CertificateDataOrBuilder>(
                getData(),
                getParentForChildren(),
                isClean());
        data_ = null;
      }
      return dataBuilder_;
    }

    private com.psiphiglobal.identity.proto.Signature selfSign_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.psiphiglobal.identity.proto.Signature, com.psiphiglobal.identity.proto.Signature.Builder, com.psiphiglobal.identity.proto.SignatureOrBuilder> selfSignBuilder_;
    /**
     * <code>.identity.proto.Signature self_sign = 7;</code>
     */
    public boolean hasSelfSign() {
      return selfSignBuilder_ != null || selfSign_ != null;
    }
    /**
     * <code>.identity.proto.Signature self_sign = 7;</code>
     */
    public com.psiphiglobal.identity.proto.Signature getSelfSign() {
      if (selfSignBuilder_ == null) {
        return selfSign_ == null ? com.psiphiglobal.identity.proto.Signature.getDefaultInstance() : selfSign_;
      } else {
        return selfSignBuilder_.getMessage();
      }
    }
    /**
     * <code>.identity.proto.Signature self_sign = 7;</code>
     */
    public Builder setSelfSign(com.psiphiglobal.identity.proto.Signature value) {
      if (selfSignBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        selfSign_ = value;
        onChanged();
      } else {
        selfSignBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.identity.proto.Signature self_sign = 7;</code>
     */
    public Builder setSelfSign(
        com.psiphiglobal.identity.proto.Signature.Builder builderForValue) {
      if (selfSignBuilder_ == null) {
        selfSign_ = builderForValue.build();
        onChanged();
      } else {
        selfSignBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.identity.proto.Signature self_sign = 7;</code>
     */
    public Builder mergeSelfSign(com.psiphiglobal.identity.proto.Signature value) {
      if (selfSignBuilder_ == null) {
        if (selfSign_ != null) {
          selfSign_ =
            com.psiphiglobal.identity.proto.Signature.newBuilder(selfSign_).mergeFrom(value).buildPartial();
        } else {
          selfSign_ = value;
        }
        onChanged();
      } else {
        selfSignBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.identity.proto.Signature self_sign = 7;</code>
     */
    public Builder clearSelfSign() {
      if (selfSignBuilder_ == null) {
        selfSign_ = null;
        onChanged();
      } else {
        selfSign_ = null;
        selfSignBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.identity.proto.Signature self_sign = 7;</code>
     */
    public com.psiphiglobal.identity.proto.Signature.Builder getSelfSignBuilder() {
      
      onChanged();
      return getSelfSignFieldBuilder().getBuilder();
    }
    /**
     * <code>.identity.proto.Signature self_sign = 7;</code>
     */
    public com.psiphiglobal.identity.proto.SignatureOrBuilder getSelfSignOrBuilder() {
      if (selfSignBuilder_ != null) {
        return selfSignBuilder_.getMessageOrBuilder();
      } else {
        return selfSign_ == null ?
            com.psiphiglobal.identity.proto.Signature.getDefaultInstance() : selfSign_;
      }
    }
    /**
     * <code>.identity.proto.Signature self_sign = 7;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.psiphiglobal.identity.proto.Signature, com.psiphiglobal.identity.proto.Signature.Builder, com.psiphiglobal.identity.proto.SignatureOrBuilder> 
        getSelfSignFieldBuilder() {
      if (selfSignBuilder_ == null) {
        selfSignBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.psiphiglobal.identity.proto.Signature, com.psiphiglobal.identity.proto.Signature.Builder, com.psiphiglobal.identity.proto.SignatureOrBuilder>(
                getSelfSign(),
                getParentForChildren(),
                isClean());
        selfSign_ = null;
      }
      return selfSignBuilder_;
    }

    private java.util.List<com.psiphiglobal.identity.proto.Signature> validations_ =
      java.util.Collections.emptyList();
    private void ensureValidationsIsMutable() {
      if (!((bitField0_ & 0x00000080) == 0x00000080)) {
        validations_ = new java.util.ArrayList<com.psiphiglobal.identity.proto.Signature>(validations_);
        bitField0_ |= 0x00000080;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.psiphiglobal.identity.proto.Signature, com.psiphiglobal.identity.proto.Signature.Builder, com.psiphiglobal.identity.proto.SignatureOrBuilder> validationsBuilder_;

    /**
     * <code>repeated .identity.proto.Signature validations = 8;</code>
     */
    public java.util.List<com.psiphiglobal.identity.proto.Signature> getValidationsList() {
      if (validationsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(validations_);
      } else {
        return validationsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .identity.proto.Signature validations = 8;</code>
     */
    public int getValidationsCount() {
      if (validationsBuilder_ == null) {
        return validations_.size();
      } else {
        return validationsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .identity.proto.Signature validations = 8;</code>
     */
    public com.psiphiglobal.identity.proto.Signature getValidations(int index) {
      if (validationsBuilder_ == null) {
        return validations_.get(index);
      } else {
        return validationsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .identity.proto.Signature validations = 8;</code>
     */
    public Builder setValidations(
        int index, com.psiphiglobal.identity.proto.Signature value) {
      if (validationsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureValidationsIsMutable();
        validations_.set(index, value);
        onChanged();
      } else {
        validationsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .identity.proto.Signature validations = 8;</code>
     */
    public Builder setValidations(
        int index, com.psiphiglobal.identity.proto.Signature.Builder builderForValue) {
      if (validationsBuilder_ == null) {
        ensureValidationsIsMutable();
        validations_.set(index, builderForValue.build());
        onChanged();
      } else {
        validationsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .identity.proto.Signature validations = 8;</code>
     */
    public Builder addValidations(com.psiphiglobal.identity.proto.Signature value) {
      if (validationsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureValidationsIsMutable();
        validations_.add(value);
        onChanged();
      } else {
        validationsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .identity.proto.Signature validations = 8;</code>
     */
    public Builder addValidations(
        int index, com.psiphiglobal.identity.proto.Signature value) {
      if (validationsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureValidationsIsMutable();
        validations_.add(index, value);
        onChanged();
      } else {
        validationsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .identity.proto.Signature validations = 8;</code>
     */
    public Builder addValidations(
        com.psiphiglobal.identity.proto.Signature.Builder builderForValue) {
      if (validationsBuilder_ == null) {
        ensureValidationsIsMutable();
        validations_.add(builderForValue.build());
        onChanged();
      } else {
        validationsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .identity.proto.Signature validations = 8;</code>
     */
    public Builder addValidations(
        int index, com.psiphiglobal.identity.proto.Signature.Builder builderForValue) {
      if (validationsBuilder_ == null) {
        ensureValidationsIsMutable();
        validations_.add(index, builderForValue.build());
        onChanged();
      } else {
        validationsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .identity.proto.Signature validations = 8;</code>
     */
    public Builder addAllValidations(
        java.lang.Iterable<? extends com.psiphiglobal.identity.proto.Signature> values) {
      if (validationsBuilder_ == null) {
        ensureValidationsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, validations_);
        onChanged();
      } else {
        validationsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .identity.proto.Signature validations = 8;</code>
     */
    public Builder clearValidations() {
      if (validationsBuilder_ == null) {
        validations_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000080);
        onChanged();
      } else {
        validationsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .identity.proto.Signature validations = 8;</code>
     */
    public Builder removeValidations(int index) {
      if (validationsBuilder_ == null) {
        ensureValidationsIsMutable();
        validations_.remove(index);
        onChanged();
      } else {
        validationsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .identity.proto.Signature validations = 8;</code>
     */
    public com.psiphiglobal.identity.proto.Signature.Builder getValidationsBuilder(
        int index) {
      return getValidationsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .identity.proto.Signature validations = 8;</code>
     */
    public com.psiphiglobal.identity.proto.SignatureOrBuilder getValidationsOrBuilder(
        int index) {
      if (validationsBuilder_ == null) {
        return validations_.get(index);  } else {
        return validationsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .identity.proto.Signature validations = 8;</code>
     */
    public java.util.List<? extends com.psiphiglobal.identity.proto.SignatureOrBuilder> 
         getValidationsOrBuilderList() {
      if (validationsBuilder_ != null) {
        return validationsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(validations_);
      }
    }
    /**
     * <code>repeated .identity.proto.Signature validations = 8;</code>
     */
    public com.psiphiglobal.identity.proto.Signature.Builder addValidationsBuilder() {
      return getValidationsFieldBuilder().addBuilder(
          com.psiphiglobal.identity.proto.Signature.getDefaultInstance());
    }
    /**
     * <code>repeated .identity.proto.Signature validations = 8;</code>
     */
    public com.psiphiglobal.identity.proto.Signature.Builder addValidationsBuilder(
        int index) {
      return getValidationsFieldBuilder().addBuilder(
          index, com.psiphiglobal.identity.proto.Signature.getDefaultInstance());
    }
    /**
     * <code>repeated .identity.proto.Signature validations = 8;</code>
     */
    public java.util.List<com.psiphiglobal.identity.proto.Signature.Builder> 
         getValidationsBuilderList() {
      return getValidationsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.psiphiglobal.identity.proto.Signature, com.psiphiglobal.identity.proto.Signature.Builder, com.psiphiglobal.identity.proto.SignatureOrBuilder> 
        getValidationsFieldBuilder() {
      if (validationsBuilder_ == null) {
        validationsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.psiphiglobal.identity.proto.Signature, com.psiphiglobal.identity.proto.Signature.Builder, com.psiphiglobal.identity.proto.SignatureOrBuilder>(
                validations_,
                ((bitField0_ & 0x00000080) == 0x00000080),
                getParentForChildren(),
                isClean());
        validations_ = null;
      }
      return validationsBuilder_;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:identity.proto.SignedCertificate)
  }

  // @@protoc_insertion_point(class_scope:identity.proto.SignedCertificate)
  private static final com.psiphiglobal.identity.proto.SignedCertificate DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.psiphiglobal.identity.proto.SignedCertificate();
  }

  public static com.psiphiglobal.identity.proto.SignedCertificate getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<SignedCertificate>
      PARSER = new com.google.protobuf.AbstractParser<SignedCertificate>() {
    public SignedCertificate parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new SignedCertificate(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<SignedCertificate> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<SignedCertificate> getParserForType() {
    return PARSER;
  }

  public com.psiphiglobal.identity.proto.SignedCertificate getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

