// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: common.proto

package com.psiphiglobal.identity.proto;

public interface SignatureOrBuilder extends
    // @@protoc_insertion_point(interface_extends:identity.proto.Signature)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string signer_cert_id = 1;</code>
   */
  java.lang.String getSignerCertId();
  /**
   * <code>string signer_cert_id = 1;</code>
   */
  com.google.protobuf.ByteString
      getSignerCertIdBytes();

  /**
   * <code>bytes data = 2;</code>
   */
  com.google.protobuf.ByteString getData();

  /**
   * <code>uint64 timestamp = 3;</code>
   */
  long getTimestamp();
}
